### PR TITLE
Add can't certify link to start, questions, and generate pages. Fixes #256.

### LINKED ISSUE #256: On all screens, we should have some escape hatch / abort
In the case we've done something wrong - including Form 8 preview, we need an escape hatch to back out the certification and reset the case.

This is pretty high urgency, it's happening a lot.

### PR DESCRIPTION
**Pull request by plusjeff**
For #256 

Start:
image

Questions:
image

Generate:
image

Known issue: On generate, the buttons and link get split across lines in a wonky way when the screen width is shrunk, but everything is still readable and clickable. Can fix this later if a priority.

@KHarshawat or @maryannbrody : Can one of you review for design?

@webinista or @paultag : Can one of you review code?

### CODE REVIEW

**Comment by plusjeff** [comment]
Some pending things still going in (i.e. don't merge yet):

- The updated content for can't certify page
- Storing data for when this happens

**Comment by plusjeff** [comment]
Updated content on can't certify page:
image

**Comment by paultag** [comment]
LGTM; kicking over to kavi -- and to confirm @plusjeff (just for myself, I know you thought about this) -- we *do* want to wipe the mailing stuff too, not just `bf14stat`?

**Comment by plusjeff** [comment]
@paultag I believe that's correct. [We're currently doing that](https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/controllers/web_controller.rb#L159)

**Comment by paultag** [comment]
@plusjeff yeah, just wanted to be sure that was intended in the case of bailout (didn't know if our this can't be certified logic was different than our bail out of caseflow logic)

**Comment by KHarshawat** [comment]
@plusjeff Can you change the second line of text to: ```The certification date was not set and any changes made in Caseflow were not saved.```

**Comment by plusjeff** [comment]
@KHarshawat Content suggestion updated!

image

**Pull request merged**
