### PR TITLE
Use Apache PDFBox instead of PDFtk for populating forms, closes #538

### LINKED ISSUE #538: PdfForms calls Process.waitpid, which isn't supported on JRuby for Windows
Caseflow fails with stacktrace below because JRuby can't invoke `wait` on an external process on Windows.

Reported to jnr-posix: https://github.com/jnr/jnr-posix/issues/65 

Most native Windows calls will fail with the `unsupported or native support failed to load` message:

https://github.com/jnr/jnr-posix/blob/master/src/main/java/jnr/posix/WindowsPOSIX.java#L483

```
NotImplementedError: waitpid unsupported or native support failed to load
              waitpid at org/jruby/RubyProcess.java:651
              waitpid at org/jruby/RubyProcess.java:639
              waitpid at org/jruby/RubyProcess.java:626
              execute at [JRUBY_HOME]/lib/ruby/gems/shared/gems/safe_shell-1.0.3/lib/safe_shell.rb:13
           call_pdftk at [JRUBY_HOME]/lib/ruby/gems/shared/gems/pdf-forms-1.0.0/lib/pdf_forms/pdftk_wrapper.rb:85
           initialize at [JRUBY_HOME]/lib/ruby/gems/shared/gems/pdf-forms-1.0.0/lib/pdf_forms/pdftk_wrapper.rb:28
                  new at [JRUBY_HOME]/lib/ruby/gems/shared/gems/pdf-forms-1.0.0/lib/pdf_forms.rb:15
  <class:FormBuilder> at [CASEFLOW]/lib/sources/caseflow/form_builder.rb:4
                <top> at [CASEFLOW]/lib/sources/caseflow/form_builder.rb:3
              require at org/jruby/RubyKernel.java:939
                <top> at [CASEFLOW]/lib/sources/caseflow.rb:1
              require at org/jruby/RubyKernel.java:939
```

### PR DESCRIPTION
**Pull request by orischwartz**
**Pros:**
* Removes environment dependency on `PDFtk`
    - No "shelling out", everything is run in jRuby process
    - No temporary PDF file writing; previous `PDFtk` implementation wrote 2 PDFs to strip the signature, here this is done in memory.
* More portable, works on all platforms

**Cons:**
* Requires jRuby. However, if we later migrate to MRI Ruby, we can switch back to `PDFtk` or any other solution by writing a class that adheres to the following interface:

```Ruby
# @param input_pdf_path The source PDF form to populate.
# @param form_values A hash of values for populating PDF form fields.
# @param output_pdf_path Output path to which populated form is written.
def fill_and_save(input_pdf_path, form_values, output_pdf_path)
end
```
For example, here is an implementation of the above interface that exactly mimics the old PDFtk logic (the temporary file has a slightly different name but this change is immaterial).
```Ruby

  class PdfFormsEngine

    def initialize
      @pdf_forms = PdfForms.new(`which pdftk`.chomp)
    end

    def fill_and_save(input_pdf_path, form_values, output_pdf_path)
      tmp_location = "#{output_pdf_path}.tmp"
      self.pdf_forms.fill_form(input_pdf_path, tmp_location, form_values, flatten: true)
      # Run it through `pdftk cat`. The reason for this is that editable PDFs have
      # an RSA signature on them which proves they are genuine. pdftk tries to
      # maintain the editability of a PDF after processing it, but then the
      # signature doesn't match. The result is that (without `pdftk cat`) Acrobat
      # shows a warning (other PDF viewers don't care).
      self.pdf_forms.call_pdftk(tmp_location, "cat", "output", output_pdf_path)
      # Remove it from the tmp_location, leaving it only in final_location
      File.delete(tmp_location)
    end
  end
```

### CODE REVIEW

**Comment by paultag** [comment]
This PR seems to have a dep on #590 - wait until that's merged before this :)

**Comment by paultag** [comment]
First pass, things look good, needs a bit of shakedown before merge.

This also strikes me as an interesting way to make assertions about the filling out of the PDF when testing, we could stub out the fill method to store it in a hash, and make assertions on the passed data. That could be good.

**Comment by paultag** [comment]
(Tests are failing, though)

**Comment by orischwartz** [comment]
@paultag I'll check. Test is failing with `The command "./bin/rake assets:precompile" exited with 1.` But this pull doesn't touch any assets.

**Comment by orischwartz** [comment]
@paultag What other changes did you have in mind for this?

**Pull request closed without merging**
