### PR TITLE
Add task column to Attorney Queue view.

### LINKED ISSUE #8731: Display task column in attorney queue table view
Soon, we are allowing judges to send rewrite tasks back to attorneys (https://github.com/department-of-veterans-affairs/caseflow/issues/8233), we want to help them distinguish these tasks from decision drafting tasks. 

Related, for judges: https://github.com/department-of-veterans-affairs/caseflow/issues/8652

### PR DESCRIPTION
**Pull request by kevmo**
Resolves #8731 

### Description

Add task column to Attorney Queue view by using built-in option on React `TaskTable` component.

**Before**:
before

**After**:
after

### CODE REVIEW

**Comment by lowellrex** [comment]
Two requests:
1. Can we add a before/after screenshot of an attorney's queue to this PR's description?
2. Can we add an assertion that checks for this column's existence in [an existing attorney queue front-end test](https://github.com/department-of-veterans-affairs/caseflow/blob/master/spec/feature/queue/attorney_queue_spec.rb)?

**Comment by kevmo** [comment]
@lowellrex Ready for your re-review.

**Comment by lowellrex** [comment]
Looks good! Can we add a `label` to `AttorneyTask` (perhaps "Draft decision") similar to [what we do for the judge tasks](https://github.com/department-of-veterans-affairs/caseflow/blob/9ec4827561750b73ee119cd8e610789033301ebd/app/models/tasks/judge_decision_review_task.rb#L16).

**Comment by laurjpeterson** [comment]
@lowellrex @kevmo - before we deploy this, i want to check. do we have a label for attorney rewrite tasks so they can distinguish those from Draft decisions?

**Pull request merged**
