### PR TITLE
Moved Other checkbox to be closer to Specify Other input text box, fixes #11

### LINKED ISSUE #11: Other explanation box appears far away from other checkbox
image

Environment:
- IE9

Steps to recreate:

1. Go to Caseflow base URL
1. Enter a BFKEY that for a veteran with missing VBMS details
1. Click Continue twice
1. On question 13, select the checkbox for other

Desired outcome:

Other textbox appears directly under or beside the Other checkbox.

### PR DESCRIPTION
**Pull request by plusjeff**
Small fix for #11 , by swapping ordering of  *Dental* and *Other*.

image

### CODE REVIEW

**Comment by alex** [comment]
@plusjeff this only makes a difference on narrow viewports, is that right?

**Comment by plusjeff** [comment]
@alex Yep! For full screen, it's on the bottom row, just in the last column.  Still adjacent.

**Comment by alex** [comment]
@plusjeff cool -- one other small question: does this change from the order they're in on the paper work, does that matter?

otherwise looks good to me, I'll let @KHarshawat have the last word.

**Comment by plusjeff** [comment]
Nope -- no change to the paperwork.

**Comment by plusjeff** [comment]
It does put it in a different order than the paper work. Although, if you look at the PDF, Other is awkwardly below things.

**Comment by plusjeff** [comment]
@KHarshawat Ready for your review.

**Pull request merged**
