### PR TITLE
Add foreign keys for request-issues-related tables (Phase 7)

### PR DESCRIPTION
**Pull request by yoomlam**
Bumps #14732
* This is phase 7 of a [multi-phase plan](https://hackmd.io/wum2LtUfSHC-1o6-peBseQ) to add missing foreign keys.
* (Skipping Phase 6 because there was a mixup with 5b and 5c.)
* Phase 5c PR #16263.
* Phase 5b PR #16281.
* Phase 4 PR #16137.
* Phase 3 PR #16120.
* Phase 2 PR #16114.
* Phase 1 PR #16034 has more details.

### Description
Add foreign keys for request-issues-related tables, i.e., `` tables. 

### Acceptance Criteria
- [ ] Code compiles correctly

### Testing Plan
Check that these all return empty arrays in prod, UAT, and Preprod.
```ruby
LegacyIssueOptin.includes(:request_issue).where.not(request_issue_id: nil).select{|r| r.request_issue == nil}.pluck(:id)

LegacyIssue.includes(:request_issue).where.not(request_issue_id: nil).select{|r| r.request_issue == nil}.pluck(:id)

# To prevent PG::QueryCanceled: ERROR:  canceling statement due to statement timeout
ActiveRecord::Base.connection.execute   "SET statement_timeout = 1800000"
# Don't show extremely long SQL statement
ActiveRecord::Base.logger.level = :warn

RequestDecisionIssue.includes(:request_issue).where.not(request_issue_id: nil).select{|r| r.request_issue == nil}.pluck(:id)

RequestDecisionIssue.includes(:decision_issue).where.not(decision_issue_id: nil).select{|r| r.decision_issue == nil}.pluck(:id)

RequestIssue.includes(:correction_request_issue).where.not(corrected_by_request_issue_id: nil).select{|r| r.correction_request_issue == nil}.pluck(:id)

RequestIssue.includes(:ineligible_due_to).where.not(ineligible_due_to_id: nil).select{|r| r.ineligible_due_to == nil}.pluck(:id)
```

### Database Changes

* [x] Have your migration classes inherit from `Caseflow::Migration`, especially when adding indexes (use `add_safe_index`)
* [ ] Verify that `migrate:rollback` works as desired ([`change` supported functions](https://edgeguides.rubyonrails.org/active_record_migrations.html#using-the-change-method))
* [ ] DB schema docs updated with `make docs` (after running `make migrate`)
* [ ] #appeals-schema notified with summary and link to this PR

### CODE REVIEW

**Comment by yoomlam** [comment]
Things to fix in UAT:
```ruby
lio=LegacyIssueOptin.includes(:request_issue).where.not(request_issue_id: nil).select{|r| r.request_issue == nil};
lio.count
=> 10

LegacyIssue.includes(:request_issue).where.not(request_issue_id: nil).select{|r| r.request_issue == nil}.pluck(:id).count
=> 0
```

**Comment by wdrougas-tista** [comment]
Validated all data is clean in prod, UAT, and preprod. Unable to confirm rollback due to the 5c migrations I think though? They were working last Friday though

**Comment by yoomlam** [comment]
> Validated all data is clean in prod, UAT, and preprod. Unable to confirm rollback due to the 5c migrations I think though? They were working last Friday though

@wdrougas-tista 
I did 2 migrates and 2 rollbacks. It worked fine for me. You may need to do a `make reset`.

**Comment by wdrougas-tista** [comment]
> > Validated all data is clean in prod, UAT, and preprod. Unable to confirm rollback due to the 5c migrations I think though? They were working last Friday though
> 
> @wdrougas-tista
> I did 2 migrates and 2 rollbacks. It worked fine for me. You may need to do a `make reset`.

Rollback now working and should be ready to be merged

**Review by wdrougas-tista — APPROVED** [review]

**Pull request merged**
