### PR TITLE
Form8 new wording and logic, closes #570

### LINKED ISSUE #570: New wording and logic for form 8 -- question 8.
Hey, @webinista, 

We have a small change on question 8 on Form 8 in Caseflow. Can we please change the whole question to the following logic.... 

Let @KHarshawat know if you'd prefer to see a quick mockup of this. Thanks!!

8A* Representative Name: 
_Text Field_
	
* Represetnative Type:
- Attorney
- Organization
- Agent
- Other

Specify Other
*_Text field_

8B.  
What is the authority for recognizing such representative in this appeal?* *_Radio Buttons_
- POA
- Certification that valid POA is in another VA file [SPECIFY FILE] 

If 8A = "Agent"; Show 8C
Is Agent on accredited list?*
<Radio Buttons>
- Yes
- No 

If 8A = "Organization"; Show 9a
Is VA Form 646, or equivalent, of record?*
<Radio Buttons>
- Yes 
- No

If 9a = "No"; Show 9b
Why is the Form 646 not of record?*
<Text Field>

### PR DESCRIPTION
**Pull request by shanear**
fixes #570

### CODE REVIEW

**Comment by orischwartz** [comment]
Only issue I see is that we need to add show/hide logic for the following:

> If 9a = "No"; Show 9b

And I think we've been using convention of branch name= issue #xxx, and pull title contains phrase `closes #xxx`

**Comment by shanear** [comment]
9b is shown either way, which is a problem captured in #585

Thanks for letting me know about the conventions, will follow them next time.

**Comment by orischwartz** [comment]
So we'll show/hide 9B as a fix for #585? If so this one is good to go. I was confused because #570 also discusses.

**Comment by shanear** [comment]
@orischwartz Yeah, that's the plan.

**Pull request merged**
