### PR TITLE
Changing style of "Yes, I'm sure" button. closes #395

### LINKED ISSUE #395: Make "Yes I'm sure button" on cancel certification modal a solid red
See [secondary button](https://playbook.cio.gov/designstandards/buttons/) styles.

### PR DESCRIPTION
**Pull request by webinista**
Adds `.cf-btn-faux`, `.cf-btn-faux--secondary` classes that make links mimic the look of buttons.

### CODE REVIEW

**Comment by alex** [comment]
@webinista can you post a screenshot? @KHarshawat I suspect you're the most appropriate reviewer? This CSS is above me.

**Comment by webinista** [comment]
screen shot 2015-12-17 at 10 06 50 am

**Comment by KHarshawat** [comment]
@webinista is this using the default secondary red button from WDS? Just checking cause there looks like a lot of CSS changes in this PR.

image

**Comment by webinista** [comment]
@KHarshawat It isn't, because `Yes, I'm sure` is an `a` element rather than `button.` I added CSS to make it look the same. 

Using `button` instead of `a` would require adding JavaScript to redirect to the error page when the button was clicked. We can do it, but an `a` element makes more semantic sense.

**Comment by alex** [comment]
I think this approach makes sense, maybe we should ask for WDS to make a
"make-a-link-look-like-a-button" style like bootstrap has?

On Thu, Dec 17, 2015 at 2:32 PM, Tiffany Brown <notifications@github.com>
wrote:

> @KHarshawat <https://github.com/KHarshawat> It isn't, because Yes, I'm
> sure is an a element rather than button. I added CSS to make it look the
> same.
>
> Using button instead of a would require adding JavaScript to redirect to
> the error page when the button was clicked. We can do it, but an a
> element makes more semantic sense.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/department-of-veterans-affairs/caseflow/pull/407#issuecomment-165557412>
> .
>



-- 
"I disapprove of what you say, but I will defend to the death your right to
say it." -- Evelyn Beatrice Hall (summarizing Voltaire)
"The people's good is the highest law." -- Cicero
GPG Key fingerprint: 125F 5C67 DFE9 4084

**Pull request merged**
