### PR TITLE
Integrates SCSS from web design standards

### PR DESCRIPTION
**Pull request by webinista**
Also begins refactoring of header, footer to bring them in line with Web Design Standards.

### CODE REVIEW

**Comment by alex** [comment]
@webinista can you attach a screenshot of what it looks like now?

**Comment by webinista** [comment]
Sure...Actually now that I think about it, we may want to wait to merge. This PR is literally about adding the SCSS files and doing a small header tweak.

screen shot 2015-11-12 at 3 23 20 pm

**Comment by plusjeff** [comment]
@webinista : Does PR #171 invalidate this one? (i.e. should we close this one or should I test/review this ticket first)

**Comment by webinista** [comment]
Not 100% sure how to answer this @plusjeff. I believe I branched this off of the 143 branch, so I _think_ it's possible to close this one and use #171 instead.

**Comment by plusjeff** [comment]
@webinista : Cool - I'll close this one, but leave the branch just in case (we can remove it later if anything is missing from #171 )

**Comment by plusjeff** [comment]
Sorry - could leave comments on lines/files because GitHub maxed out on the number of files it could show in a diff. Will leave notes in plain-old comments.

**Comment by plusjeff** [comment]
These files look like they should not be modified, based on the changes in them.

image

**Pull request closed without merging**
