### PR TITLE
Updates RampReview validations

### PR DESCRIPTION
**Pull request by sansb**
Removes receipt_date < notice_date validation, adds receipt_date < RAMP beginning validation

connects #5031 
connects #4658

### CODE REVIEW

**Comment by shanear** [comment]
```
irb(main):001:0> SyncIntakeJob.perform_now
[ActiveJob] [SyncIntakeJob] [f6a7c1c6-11e6-4137-a80b-71033e5b2739] [2018-04-10 00:37:10 -0400] Performing SyncIntakeJob (Job ID: f6a7c1c6-11e6-4137-a80b-71033e5b2739) from Shoryuken(caseflow_prod_low_priority)
[ActiveJob] [SyncIntakeJob] [f6a7c1c6-11e6-4137-a80b-71033e5b2739] [2018-04-10 00:37:10 -0400]   RampElection Load (175.6ms)  SELECT "ramp_elections".* FROM "ramp_elections" WHERE (end_product_status NOT IN ('CAN','CLR') OR end_product_status IS NULL)
[ActiveJob] [SyncIntakeJob] [f6a7c1c6-11e6-4137-a80b-71033e5b2739] [2018-04-10 00:37:11 -0400]   RampElectionIntake Load (30.8ms)  SELECT  "intakes".* FROM "intakes" WHERE "intakes"."type" IN ('RampElectionIntake') AND "intakes"."detail_id" = $1 AND "intakes"."detail_type" = $2 AND "intakes"."completion_status" = $3 ORDER BY "intakes"."completed_at" DESC LIMIT $4  [["detail_id", 1], ["detail_type", "RampElection"], ["completion_status", "success"], ["LIMIT", 1]]
[ActiveJob] [SyncIntakeJob] [f6a7c1c6-11e6-4137-a80b-71033e5b2739] [2018-04-10 00:37:11 -0400]    (3.1ms)  SELECT COUNT(*) FROM "ramp_refilings" WHERE "ramp_refilings"."ramp_election_id" = $1  [["ramp_election_id", 1]]
[ActiveJob] [SyncIntakeJob] [f6a7c1c6-11e6-4137-a80b-71033e5b2739] [2018-04-10 00:37:11 -0400]    (1.1ms)  BEGIN
[ActiveJob] [SyncIntakeJob] [f6a7c1c6-11e6-4137-a80b-71033e5b2739] [2018-04-10 00:37:11 -0400]   RampIssue Load (2.4ms)  SELECT "ramp_issues".* FROM "ramp_issues" WHERE "ramp_issues"."review_id" = $1 AND "ramp_issues"."review_type" = $2  [["review_id", 1], ["review_type", "RampElection"]]
[ActiveJob] [SyncIntakeJob] [f6a7c1c6-11e6-4137-a80b-71033e5b2739] [2018-04-10 00:37:11 -0400]    (1.1ms)  ROLLBACK
[ActiveJob] [SyncIntakeJob] [f6a7c1c6-11e6-4137-a80b-71033e5b2739] [2018-04-10 00:37:12 -0400] Error performing SyncIntakeJob (Job ID: f6a7c1c6-11e6-4137-a80b-71033e5b2739) from Shoryuken(caseflow_prod_low_priority) in 1381.46ms: NoMethodError (undefined method `each' for nil:NilClass):
/opt/caseflow-certification/src/app/models/ramp_election.rb:52:in `block in recreate_issues_from_contentions!'
/opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/activerecord-5.1.6/lib/active_record/connection_adapters/abstract/database_statements.rb:235:in `block in transaction'
/opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/activerecord-5.1.6/lib/active_record/connection_adapters/abstract/transaction.rb:194:in `block in within_new_transaction'
/opt/rbenv/versions/2.2.4/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
/opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/activerecord-5.1.6/lib/active_record/connection_adapters/abstract/transaction.rb:191:in `within_new_transaction'
/opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/activerecord-5.1.6/lib/active_record/connection_adapters/abstract/database_statements.rb:235:in `transaction'
/opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/activerecord-5.1.6/lib/active_record/transactions.rb:210:in `transaction'
/opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/activerecord-5.1.6/lib/active_record/transactions.rb:299:in `transaction'
/opt/caseflow-certification/src/app/models/ramp_election.rb:49:in `recreate_issues_from_contentions!'
/opt/caseflow-certification/src/app/jobs/sync_intake_job.rb:13:in `block in perform'
/opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/activerecord-5.1.6/lib/active_record/relation/delegation.rb:39:in `each'
/opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/activerecord-5.1.6/lib/active_record/relation/delegation.rb:39:in `each'
/opt/caseflow-certification/src/app/jobs/sync_intake_job.rb:7:in `perform'
/opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/activejob-5.1.6/lib/active_job/execution.rb:37:in `block in perform_now'
/opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/activesupport-5.1.6/lib/active_support/callbacks.rb:108:in `block in run_callbacks'
/opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/sentry-raven-2.7.1/lib/raven/integrations/rails/active_job.rb:18:in `call'
/opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/sentry-raven-2.7.1/lib/raven/integrations/rails/active_job.rb:18:in `capture_and_reraise_with_sentry'
/opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/sentry-raven-2.7.1/lib/raven/integrations/rails/active_job.rb:12:in `block (2 levels) in included'
/opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/activesupport-5.1.6/lib/active_support/callbacks.rb:117:in `instance_exec'
/opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/activesupport-5.1.6/lib/active_support/callbacks.rb:117:in `block in run_callbacks'
/opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/i18n-1.0.0/lib/i18n.rb:268:in `with_locale'
/opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/activejob-5.1.6/lib/active_job/translation.rb:7:in `block (2 levels) in <module:Translation>'
/opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/activesupport-5.1.6/lib/active_support/callbacks.rb:117:in `instance_exec'
/opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/activesupport-5.1.6/lib/active_support/callbacks.rb:117:in `block in run_callbacks'
/opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/activejob-5.1.6/lib/active_job/logging.rb:24:in `call'
/opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/activejob-5.1.6/lib/active_job/logging.rb:24:in `block (4 levels) in <module:Logging>'
/opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/activesupport-5.1.6/lib/active_support/notifications.rb:166:in `block in instrument'
/opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/activesupport-5.1.6/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
/opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/activesupport-5.1.6/lib/active_support/notifications.rb:166:in `instrument'
/opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/activejob-5.1.6/lib/active_job/logging.rb:23:in `block (3 levels) in <module:Logging>'
/opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/activejob-5.1.6/lib/active_job/logging.rb:44:in `block in tag_logger'
/opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/activesupport-5.1.6/lib/active_support/tagged_logging.rb:69:in `block in tagged'
/opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/activesupport-5.1.6/lib/active_support/tagged_logging.rb:26:in `tagged'
/opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/activesupport-5.1.6/lib/active_support/tagged_logging.rb:69:in `tagged'
/opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/activejob-5.1.6/lib/active_job/logging.rb:44:in `tag_logger'
/opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/activejob-5.1.6/lib/active_job/logging.rb:20:in `block (2 levels) in <module:Logging>'
/opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/activesupport-5.1.6/lib/active_support/callbacks.rb:117:in `instance_exec'
/opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/activesupport-5.1.6/lib/active_support/callbacks.rb:117:in `block in run_callbacks'
/opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/activesupport-5.1.6/lib/active_support/callbacks.rb:135:in `call'
/opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/activesupport-5.1.6/lib/active_support/callbacks.rb:135:in `run_callbacks'
/opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/activejob-5.1.6/lib/active_job/execution.rb:33:in `perform_now'
/opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/activejob-5.1.6/lib/active_job/execution.rb:16:in `perform_now'
(irb):1:in `irb_binding'
/opt/rbenv/versions/2.2.4/lib/ruby/2.2.0/irb/workspace.rb:86:in `eval'
/opt/rbenv/versions/2.2.4/lib/ruby/2.2.0/irb/workspace.rb:86:in `evaluate'
/opt/rbenv/versions/2.2.4/lib/ruby/2.2.0/irb/context.rb:379:in `evaluate'
/opt/rbenv/versions/2.2.4/lib/ruby/2.2.0/irb.rb:489:in `block (2 levels) in eval_input'
/opt/rbenv/versions/2.2.4/lib/ruby/2.2.0/irb.rb:623:in `signal_status'
/opt/rbenv/versions/2.2.4/lib/ruby/2.2.0/irb.rb:486:in `block in eval_input'
/opt/rbenv/versions/2.2.4/lib/ruby/2.2.0/irb/ruby-lex.rb:245:in `block (2 levels) in each_top_level_statement'
/opt/rbenv/versions/2.2.4/lib/ruby/2.2.0/irb/ruby-lex.rb:231:in `loop'
/opt/rbenv/versions/2.2.4/lib/ruby/2.2.0/irb/ruby-lex.rb:231:in `block in each_top_level_statement'
/opt/rbenv/versions/2.2.4/lib/ruby/2.2.0/irb/ruby-lex.rb:230:in `catch'
/opt/rbenv/versions/2.2.4/lib/ruby/2.2.0/irb/ruby-lex.rb:230:in `each_top_level_statement'
/opt/rbenv/versions/2.2.4/lib/ruby/2.2.0/irb.rb:485:in `eval_input'
/opt/rbenv/versions/2.2.4/lib/ruby/2.2.0/irb.rb:395:in `block in start'
/opt/rbenv/versions/2.2.4/lib/ruby/2.2.0/irb.rb:394:in `catch'
/opt/rbenv/versions/2.2.4/lib/ruby/2.2.0/irb.rb:394:in `start'
/opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/railties-5.1.6/lib/rails/commands/console/console_command.rb:62:in `start'
/opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/railties-5.1.6/lib/rails/commands/console/console_command.rb:17:in `start'
/opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/railties-5.1.6/lib/rails/commands/console/console_command.rb:97:in `perform'
/opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
/opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
/opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
/opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/railties-5.1.6/lib/rails/command/base.rb:63:in `perform'
/opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/railties-5.1.6/lib/rails/command.rb:44:in `invoke'
/opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/railties-5.1.6/lib/rails/commands.rb:16:in `<top (required)>'
bin/rails:4:in `require'
bin/rails:4:in `<main>'
NoMethodError: undefined method `each' for nil:NilClass
	from app/models/ramp_election.rb:52:in `block in recreate_issues_from_contentions!'
	from app/models/ramp_election.rb:49:in `recreate_issues_from_contentions!'
	from app/jobs/sync_intake_job.rb:13:in `block in perform'
	from app/jobs/sync_intake_job.rb:7:in `perform'
	from (irb):1
```

crashed pretty fast 😢

**Comment by shanear** [comment]
changing this line:

`RampElection.active.each do |ramp_election|`

to this 

`RampElection.established.active.each do |ramp_election|`

seems to have improved the situation though

**Comment by shanear** [comment]
Andddd... the second error. Apparently some of the users have been changed... :doh:

```
D, [2018-04-10T00:42:15.031736 #12278] DEBUG -- : <?xml version='1.0' encoding='UTF-8'?><S:Envelope xmlns:S="http://schemas.xmlsoap.org/soap/envelope/"><S:Body><S:Fault xmlns:ns4="http://www.w3.org/2003/05/soap-envelope"><faultcode>S:Client</faultcode><faultstring>ID: 53028091-6231-439E-8FA6-6192ACD7B4A7: Logon ID AMCCBELL Not Found</faultstring></S:Fault></S:Body></S:Envelope>
Savon::SOAPFault: (S:Client) ID: 53028091-6231-439E-8FA6-6192ACD7B4A7: Logon ID AMCCBELL Not Found
	from app/services/external_api/bgs_service.rb:31:in `block in get_end_products'
	from app/services/metrics_service.rb:12:in `block in record'
	from app/services/metrics_service.rb:11:in `record'
	from app/services/external_api/bgs_service.rb:28:in `get_end_products'
	from app/models/veteran.rb:108:in `fetch_end_products'
	from app/models/veteran.rb:59:in `end_products'
	from app/models/ramp_election.rb:84:in `fetch_established_end_product'
	from app/models/ramp_election.rb:37:in `established_end_product'
	from app/models/ramp_election.rb:64:in `sync_ep_status!'
	from (irb):32:in `block in irb_binding'
	from (irb):25
```

**Comment by shanear** [comment]
but thanks to Chris, i now have an ultimate sensitivity user to run the script with. It seems to be working

**Comment by shanear** [comment]
```
ActiveRecord::RecordInvalid: Validation failed: Receipt date before_ramp
	from app/models/ramp_election.rb:63:in `sync_ep_status!'
	from (irb):49:in `block in irb_binding'
	from (irb):37
```

and we also have some bad receipt dates

**Comment by sansb** [comment]
@shanear 

Who is the ultimate sensitivity user? Can we change the script to always run as that user?

And what shall we do about the bad receipt dates? Set them to the RAMP start date?

**Comment by shanear** [comment]
Data fix update

```
RampElection.where(receipt_date: (10.years.ago...Date.new(2017, 11, 1))).each { |e| puts e.receipt_date }
```
returns

```
2017-03-08
2012-03-06
2017-03-07
2017-03-09
2017-03-19
2016-03-29
2014-03-24
2017-03-06
2016-02-11
2010-03-10
2016-03-14
2016-03-14
```

These all look like the year was incorrectly inputed. It can only be 2018

Fixing them with this script:

```
RampElection.where(receipt_date: (10.years.ago...Date.new(2017, 11, 1))).each do |re|
  puts Date.new(2018, re.receipt_date.month, re.receipt_date.day)
  re.update!(receipt_date: Date.new(2018, re.receipt_date.month, re.receipt_date.day))
end
```

Which will change them to:
```
2018-03-08
2018-03-06
2018-03-07
2018-03-09
2018-03-19
2018-03-29
2018-03-24
2018-03-06
2018-02-11
2018-03-10
2018-03-14
2018-03-14
```

**Comment by sansb** [comment]
@shanear check this out- 

https://github.com/department-of-veterans-affairs/caseflow/blob/6b4fbc14b1eabdff789c3487854935c75bbadd98/app/models/user.rb#L176-L181

used here: 
https://github.com/department-of-veterans-affairs/caseflow/blob/6b4fbc14b1eabdff789c3487854935c75bbadd98/app/controllers/api/application_controller.rb#L28-L30

**Comment by shanear** [comment]
lol 10 years ago was too few years:
```
RampElection.active.where(end_product_status_last_synced_at: 20.years.ago..1.day.ago).each { |e| puts e.receipt_date }
```

returns

```
2008-03-12
0018-02-22
0008-03-21
0018-03-26
0208-03-12
2008-03-12
0018-03-15
```

year 8 AD 😄

fixing all of these:

```
RampElection.active.where(end_product_status_last_synced_at: 20.years.ago..1.day.ago).each do |re|
  puts Date.new(2018, re.receipt_date.month, re.receipt_date.day)
  re.update!(receipt_date: Date.new(2018, re.receipt_date.month, re.receipt_date.day))
end
```

**Pull request merged**
