### PR TITLE
Find active child TimedHoldTask without New Query

### PR DESCRIPTION
**Pull request by lomaxap**
Issue surfaced in #11882, `children.open` runs a new query. For `GenericQueues` this results in an an n+1 query. Filter open child tasks in find block  instead of using the `open` method

### CODE REVIEW

**Comment by tomas-nava** [comment]
😢 the test failures in circle are happening for me locally as well; I'm not sure why, as the method returns identical results during these tests both before and after your change. Maybe the original query causes cached objects to reload?

**Comment by lomaxap** [comment]
> Maybe the original query causes cached objects to reload?

I added a bunch of reload statements to the failing tests and this resolved the issue. This method effectively ensured tasks were always up-to-date.

**Comment by ferristseng** [comment]
Is there any documentation about what `open` is supposed to do? I couldn't find any searching around.

**Comment by lomaxap** [comment]
> Is there any documentation about what `open` is supposed to do? I couldn't find any searching around.

I don't think there's any documentation on it, but `open` is a [scope method](https://api.rubyonrails.org/classes/ActiveRecord/Scoping/Named/ClassMethods.html) that [limits tasks](https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/models/task.rb#L44) to those with open statuses. So instead of having to write `Task.where(status: open_statuses)` all the time, you can just write `Task.open`.

**Pull request merged**
