### PR TITLE
Load the fonts we want from Google fonts

### PR DESCRIPTION
**Pull request by alex**
screen shot 2016-01-05 at 1 18 25 pm

### CODE REVIEW

**Comment by alex** [comment]
Will confirm this works in a local IE VM, we should probably also validate it works on the VA IE configuration.

**Comment by paultag** [comment]
Do we want to add the network dependency to Google or should we pull that down. I seem to recall the USDS Design Standards pulling them into the project 

I don't really have an opinion on this -- is the URL (including the SSN) sent in the HTTP Referrer to the Google servers?

**Comment by alex** [comment]
CDN seems easiest to me, I'm in favor of just doing that (my experience
with trying to use the rails asset pipeline for fonts was really bad)

On Tue, Jan 5, 2016 at 1:25 PM, <notifications@github.com> wrote:

> Do we want to add the network dependency to Google or should we pull that
> down. I seem to recall the USDS Design Standards pulling them into the
> project
>
> I don't really have an opinion on this -- is the URL (including the SSN)
> sent in the HTTP Referrer to the Google servers?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/department-of-veterans-affairs/caseflow/pull/490#issuecomment-169088794>
> .
>



-- 
"I disapprove of what you say, but I will defend to the death your right to
say it." -- Evelyn Beatrice Hall (summarizing Voltaire)
"The people's good is the highest law." -- Cicero
GPG Key fingerprint: 125F 5C67 DFE9 4084

**Comment by alex** [comment]
Confirmed it works in IE, still need to test in a VA IE :-)

**Comment by alex** [comment]
Doesn't work on VA IE, they appear to have disabled webfonts. Suggest we land as is since we're in the process of getting people a chrome.

**Pull request merged**
