### PR TITLE
Removes 'Built with <3 by Digital Service at VA' from the Caseflow footer

### LINKED ISSUE #5268: Remove "Built with <3 by Digital Service at VA" from the Caseflow footer
@nicholasholtz expressed the thought that we should get away from DS branding on Caseflow in preparation for the eventual DS rolloff of the project. 

Kicking this to design/product for async discussion whenever convenient.

### PR DESCRIPTION
**Pull request by bgantick**
Resolves #5268 

### Description
Removes "built with" text from non-react footer. This PR in in `caseflow-frontend-toolkit` removes it from react footer: https://github.com/department-of-veterans-affairs/caseflow-frontend-toolkit/pull/65

### Acceptance Criteria
- [x] Code compiles correctly

### User Facing Changes
 - [x] Screenshots of UI changes added to PR & Original Issue

### Before/After

Screen Shot 2020-10-27 at 3 45 07 PM
-----
Screen Shot 2020-10-27 at 3 45 45 PM

### CODE REVIEW

**Review by alisan16 — APPROVED** [review]
🎉

**Comment by alisan16** [comment]
@bgantick Let's merge this! Looks like you'll need to just update your branch

**Comment by ryanroyroy** [comment]
Could this be replaced by saying something similar to include the Casflow team's contribution? 

Such as "Built and maintained with <3 by Digital Services at the VA and the Caseflow team."

**Comment by alisan16** [comment]
@ryanroyroy Feel free to comment on the original ticket with your feedback https://github.com/department-of-veterans-affairs/caseflow/issues/5268

My take is it's easiest to remove it entirely since the Digital Services at the VA haven't worked on Caseflow since 2019. The application itself is already called Caseflow, so it feels redundant to say it's also built and maintained by the Caseflow team in the footer.

**Pull request merged**
