### PR TITLE
Updating react-input-autosize

### PR DESCRIPTION
**Pull request by sharonwarner**
This PR updates the react-input-autosize library to get rid of a console warning: 

screen shot 2017-05-16 at 2 06 00 pm

Connects #1731

### CODE REVIEW

**Comment by NickHeiner** [comment]
The diff in `npm-shrinkwrap.json` is larger than I'd hope... which version of npm are you using? I think there may be a mismatch between what you're using and what the last person who wrote the file used, who very well may have been me (doing it wrong) :smile:. If you're using `3.10.10` then you're doing it right, and we have no problem here.

**Comment by sharonwarner** [comment]
I'm using 4.0.5! 😧

**Comment by amprokop** [comment]
ah interesting, easiest way to adjust the version is by running `npm install -g npm@3.10.10` if you're comfortable changing your global npm v.

**Comment by sharonwarner** [comment]
I changed my npm version to 3.10.10, reran the package update on a new branch, and got identical package.json and npm-shrinkwrap.json files.

**Comment by amprokop** [comment]
can we possibly track down what's going on with the big shrinkwrap here — can you do a little research, and maybe post in the appeals-engineering room and see if anyone knows why we have so many changes here? i've had this happen and have never been sure myself, so it'd be a good thing to find out.

**Comment by sharonwarner** [comment]
Followed the directions found [here](https://github.com/npm/npm/issues/9117) to avoid huge shrinkwrap update in the future.

**Pull request merged**
