### PR TITLE
Added password placeholder text, closed #260

### LINKED ISSUE #260: Change VACOLS login form to have example text
to suggest what to enter (`RO99` or something)

### PR DESCRIPTION
**Pull request by plusjeff**
Issue #260 

image

### CODE REVIEW

**Comment by plusjeff** [comment]
@KHarshawat : Design review, plz :smile:

**Comment by KHarshawat** [comment]
@plusjeff can i haz this? 

image

**Comment by paultag** [comment]
@plusjeff looks like it's ready for design ack again? Assigning @KHarshawat - undo that if it's not ready yet!

**Comment by plusjeff** [comment]
@KHarshawat @paultag Ready

image

**Comment by paultag** [comment]
@plusjeff Showed it to Kavi - can we add padding to the left side of the `Example:` between the text and the input field?

**Comment by plusjeff** [comment]
Will do!

**Comment by plusjeff** [comment]
@KHarshawat @paultag Added 20px margin on the left side. Let me know if it should be any more/less.

image

**Comment by paultag** [comment]
Awesome, landing it. Got Kavi's ack

**Pull request merged**
