### PR TITLE
Make UI copy of queue table view more generic

### LINKED ISSUE #7665: Make queue table view description more generic
Currently the descriptions for the different tabs in the queue table view are very specific to the co-located admin team. Since this view will be the basis of all generic queues that we roll out to all of the different teams (and individuals on those teams) going forward we need to make these more generic. If it is possible to retain the current text for the colocated queue table view then we should do that. However, since they already have some experience using this view I don't think it would be a terrible outcome if we had to change the text for them as well.

| Tab | Co-located text | Generic text |
| --- | --- | --- |
| New | These are new administrative actions that have been assigned to you | These are cases that require some action from you |
| Pending action | When a hold is complete, the case will appear here. Cases with new documents will also appear here | These are cases that have been assigned to some other team (or placed on hold) require some action from you again |
| On hold | When a hold is complete, the case will automatically return to the Pending action tab | These are cases that do not require immediate action from you |
| Completed | Cases with tasks that were marked complete in the last two weeks will appeal here | _No change_ |

@sneha-pai @allyceh @laurjpeterson @joeyyang What do y'all think of this approach?

## Acceptance criteria
* [ ] More generic descriptions are displayed for all generic queues

### PR DESCRIPTION
**Pull request by joeyyang**
Resolves #7665

### Description
This PR changes the descriptions for the different tabs in the queue table view from copy specific to the co-located admin team to generic queue descriptions. 

The copy used in this PR is copy proposed by @joeyyang in https://github.com/department-of-veterans-affairs/caseflow/issues/7665. 

We are seeking approval for this copy from @laurjpeterson, @sneha-pai, and @allyceh. Happy to discuss in the comments, just wanted to start by proposing something. 

Notes:
- I'm not sure I like the descriptions as a `p` — was thinking a small heading like `h4`, but I'm unfamiliar with the style guide so will defer to the designer.
- Unfamiliar with exactly all the use cases, but want to confirm that the text for the "Pending action" tab is accurate.

### Acceptance Criteria
- [x] UI text approval from @laurjpeterson 
- [ ] UI text approval from @sneha-pai 
- [ ] UI text approval from @allyceh 

screenshot 2018-11-02 10 53 09
screenshot 2018-11-02 10 53 14
screenshot 2018-11-02 10 53 18
screenshot 2018-11-02 10 53 24

### CODE REVIEW

**Comment by joeyyang** [comment]
per @laurjpeterson review just now, I will make these changes:
"Cases assigned back to you" -> "Cases no longer on hold"
"When hold is released"  -> "When hold is completed"

**Comment by joeyyang** [comment]
@laurjpeterson @lowellrex changes made to the copy per LP's suggestions; please review and approve!

**Comment by sneha-pai** [comment]
I agree @joey that the descriptions are not as effective in  p 

Let's try h4 instead (across all descriptions under tabs). Also, can the padding between tab and description be smaller than the space between the description and the table content? It appears as equidistant at the moment.

**Comment by joeyyang** [comment]
> I agree @joeyyang that the descriptions are not as effective in p
> 
> Let's try h4 instead (across all descriptions under tabs). Also, can the padding between tab and description be smaller than the space between the description and the table content? It appears as equidistant at the moment.

Whoops! This comment came in after I tagged `ready-to-merge` — added a new issue for this here: https://github.com/department-of-veterans-affairs/caseflow/issues/7791

**Pull request merged**
