### PR TITLE
Add missing foreign keys to the users table (Phase 1)

### PR DESCRIPTION
**Pull request by yoomlam**
Bumps #14732
This is phase 1 of a [multi-phase plan](https://hackmd.io/wum2LtUfSHC-1o6-peBseQ) to add missing foreign keys.

Resolves lack of foreign keys. See https://thoughtbot.com/blog/referential-integrity-with-foreign-keys
[Slack discussion](https://dsva.slack.com/archives/CQTDX9BF0/p1616429065002700)

### Description
Add foreign keys to the `users` table. 

FYI: StrongMigrations' suggestion:
```
=== Dangerous operation detected #strong_migrations ===

New foreign keys are validated by default. This acquires an AccessExclusiveLock,
which is expensive on large tables. Instead, validate it in a separate migration
with a more agreeable RowShareLock.

class StrongMigrations::Checker < ActiveRecord::Migration[5.2]
  def change
    add_foreign_key "cavc_remands", "users", column: "created_by_id", validate: false
  end
end

class ValidateStrongMigrations::Checker < ActiveRecord::Migration[5.2]
  def change
    validate_foreign_key "cavc_remands", "users"
  end
end
```

### Acceptance Criteria
- [ ] Code compiles correctly

### Testing Plan
Before deployment, rerun the following to ensure the foreign keys will be valid:
```ruby
CavcRemand.includes(:created_by).where.not(created_by_id: nil).select{|cr| cr.created_by == nil}.count
=> 0
CavcRemand.includes(:updated_by).where.not(updated_by_id: nil).select{|cr| cr.updated_by == nil}.count
=> 0
VirtualHearing.includes(:created_by).where.not(created_by_id: nil).select{|cr| cr.created_by == nil}.count
=> 0

Task.includes(:assigned_by).where.not(assigned_by_id: nil).select{|cr| cr.assigned_by == nil}.count
=> 0
Task.includes(:cancelled_by).where.not(cancelled_by_id: nil).select{|cr| cr.cancelled_by == nil}.count
=> 0

Distribution.includes(:judge).where.not(judge_id: nil).select{|cr| cr.judge == nil}.count
=> 0
Hearing.includes(:judge).where.not(judge_id: nil).select{|cr| cr.judge == nil}.count
=> 0
HearingDay.includes(:judge).where.not(judge_id: nil).select{|cr| cr.judge == nil}.count
=> 0
SentHearingEmailEvent.includes(:sent_by).where.not(sent_by_id: nil).select{|cr| cr.sent_by == nil}.count
=> 0

JudgeCaseReview.includes(:attorney).where.not(attorney_id: nil).select{|cr| cr.attorney == nil}.count
=> 0
JudgeCaseReview.includes(:judge).where.not(judge_id: nil).select{|cr| cr.judge == nil}.count
=> 0
```

### Database Changes
*Only for Schema Changes*

* [x] Have your migration classes inherit from `Caseflow::Migration`, especially when adding indexes (use `add_safe_index`)
* [x] Verify that `migrate:rollback` works as desired ([`change` supported functions](https://edgeguides.rubyonrails.org/active_record_migrations.html#using-the-change-method))
* [x] DB schema docs updated with `make docs` (after running `make migrate`)
* [x] #appeals-schema notified with summary and link to this PR

### CODE REVIEW

**Comment by nanotone** [comment]
This looks good according to StrongMigration's suggestion, but I do have a few clarifying questions:
- What happens if there are, for some improbable reason, still invalid foreign keys at time of deployment? Will the first or second migration fail?
- If the second migration fails, I don't think the first migration will be rolled back by the deployment process. Is this something to worry about?

**Comment by yoomlam** [comment]
> This looks good according to StrongMigration's suggestion, but I do have a few clarifying questions:
> 
> * What happens if there are, for some improbable reason, still invalid foreign keys at time of deployment? Will the first or second migration fail?

I'm thinking the second since the first does no validation.

> * If the second migration fails, I don't think the first migration will be rolled back by the deployment process. Is this something to worry about?

That's probably a good thing. All or nothing. I don't want the DB to be in an intermediate state.

**Comment by nanotone** [comment]
> >- If the second migration fails, I don't think the first migration will be rolled back by the deployment process. Is this something to worry about?

>That's probably a good thing. All or nothing. I don't want the DB to be in an intermediate state.

My point was that it doesn't sound like an all-or-nothing. The deployment will fail and stay at the previous Git commit, but if the first migration doesn't rollback, then the DB will have the un-validated index already created. That's going to prevent the commit from getting applied again.

**Comment by yoomlam** [comment]
> > > * If the second migration fails, I don't think the first migration will be rolled back by the deployment process. Is this something to worry about?
> 
> > That's probably a good thing. All or nothing. I don't want the DB to be in an intermediate state.
> 
> My point was that it doesn't sound like an all-or-nothing. The deployment will fail and stay at the previous Git commit, but if the first migration doesn't rollback, then the DB will have the un-validated index already created. That's going to prevent the commit from getting applied again.

Ahh, I see. If problems arise, then we can quickly create another migration to remove the added foreign keys.

**Review by nanotone — APPROVED** [review]
Sounds and looks good to me. :shipit:

**Comment by yoomlam** [comment]
Just ran the `count` commands in the Testing Plan in prod and results are the same.

**Pull request merged**
