### PR TITLE
Fixed #17 -- added feedback links to the app

### LINKED ISSUE #17: Collect in-app feedback
We need a mechanism to collect in-app feedback during the pilot phase. Here are some options: 

- Provide a mailto link and set up an email list to collect feedback
- Create a feedback button that links to a survey (Google Sheets/ Survey Monkey)
- Use a service like UserVoice
- Others?

### PR DESCRIPTION
**Pull request by alex**

### CODE REVIEW

**Comment by alex** [comment]
screen shot 2015-11-18 at 3 21 13 pm

**Comment by KHarshawat** [comment]
@alex 

image

Background: #0071bc (primary)
Text: #fff
Note the different font weights
`Caseflow is a pilot project.` is bold 
`Have a question, feature improvement, or problem?` is normal
`Send feedback.` is underlined and a link

**Comment by KHarshawat** [comment]
image

**Comment by alex** [comment]
screen shot 2015-11-18 at 3 32 23 pm

**Pull request merged**
