### PR TITLE
validation, test for unique constraint on HearingTaskAssociation

### LINKED ISSUE #10152: Add protections to ensure that there is a 1:1 association between Hearings and HearingTasks
We have a [`has_one` association](https://github.com/department-of-veterans-affairs/caseflow/blob/97fde32d60c9fc2ad64d22c1655f04931a2da655/app/models/hearing.rb#L10) between a `Hearing` and a `HearingTask`. It's not clear how Rails enforces this association and it [doesn't look like a constraint on the database exists](https://github.com/department-of-veterans-affairs/caseflow/blob/97fde32d60c9fc2ad64d22c1655f04931a2da655/db/schema.rb#L517) to enforce this.

Add more conditions to ensure we don't end up in a situation where we have more than one hearing associated with a hearing task, or vice-versa.

### PR DESCRIPTION
**Pull request by tomas-nava**
Resolves #10152

### Description
Adds a validation to ensure a 1:1 relationship between hearings and open hearing tasks.

### CODE REVIEW

**Comment by lomaxap** [comment]
FYI, I found 17 `HearingTaskAssociation`s with duplicate hearing ids. I can take a look before you deploy this to resolve these.
```
{"84987-LegacyHearing"=>
  [#<HearingTaskAssociation:0x00005597ac532d40
    id: 54,
    hearing_type: "LegacyHearing",
    hearing_id: 84987,
    hearing_task_id: 41092>,
   #<HearingTaskAssociation:0x00005597ae39b778
    id: 10162,
    hearing_type: "LegacyHearing",
    hearing_id: 84987,
    hearing_task_id: 215773>],
 "101424-LegacyHearing"=>
  [#<HearingTaskAssociation:0x00005597ac2bae00
    id: 10916,
    hearing_type: "LegacyHearing",
    hearing_id: 101424,
    hearing_task_id: 227596>,
   #<HearingTaskAssociation:0x00005597ae0a4da8
    id: 7354,
    hearing_type: "LegacyHearing",
    hearing_id: 101424,
    hearing_task_id: 40889>],
 "96710-LegacyHearing"=>
  [#<HearingTaskAssociation:0x00005597abd28d70
    id: 10942,
    hearing_type: "LegacyHearing",
    hearing_id: 96710,
    hearing_task_id: 227802>,
   #<HearingTaskAssociation:0x00005597ae6f2b10
    id: 5178,
    hearing_type: "LegacyHearing",
    hearing_id: 96710,
    hearing_task_id: 107998>],
 "110215-LegacyHearing"=>
  [#<HearingTaskAssociation:0x00005597abbf05c0
    id: 11170,
    hearing_type: "LegacyHearing",
    hearing_id: 110215,
    hearing_task_id: 45962>,
   #<HearingTaskAssociation:0x00005597ae27cf68
    id: 12119,
    hearing_type: "LegacyHearing",
    hearing_id: 110215,
    hearing_task_id: 243132>],
 "95069-LegacyHearing"=>
  [#<HearingTaskAssociation:0x00005597ab992be8
    id: 4447,
    hearing_type: "LegacyHearing",
    hearing_id: 95069,
    hearing_task_id: 107538>,
   #<HearingTaskAssociation:0x00005597ab95f810
    id: 4448,
    hearing_type: "LegacyHearing",
    hearing_id: 95069,
    hearing_task_id: 163361>],
 "87462-LegacyHearing"=>
  [#<HearingTaskAssociation:0x00005597ab69ea40
    id: 928,
    hearing_type: "LegacyHearing",
    hearing_id: 87462,
    hearing_task_id: 42598>,
   #<HearingTaskAssociation:0x00005597ae46fc58
    id: 5843,
    hearing_type: "LegacyHearing",
    hearing_id: 87462,
    hearing_task_id: 163668>],
 "87522-LegacyHearing"=>
  [#<HearingTaskAssociation:0x00005597ab69deb0
    id: 937,
    hearing_type: "LegacyHearing",
    hearing_id: 87522,
    hearing_task_id: 69793>,
   #<HearingTaskAssociation:0x00005597ae5bf248
    id: 10329,
    hearing_type: "LegacyHearing",
    hearing_id: 87522,
    hearing_task_id: 218776>],
 "99981-LegacyHearing"=>
  [#<HearingTaskAssociation:0x00005597ab5d6b80
    id: 10788,
    hearing_type: "LegacyHearing",
    hearing_id: 99981,
    hearing_task_id: 225016>,
   #<HearingTaskAssociation:0x00005597ae400038
    id: 6724,
    hearing_type: "LegacyHearing",
    hearing_id: 99981,
    hearing_task_id: 127454>],
 "107249-LegacyHearing"=>
  [#<HearingTaskAssociation:0x00005597ab532418
    id: 9774,
    hearing_type: "LegacyHearing",
    hearing_id: 107249,
    hearing_task_id: 212325>,
   #<HearingTaskAssociation:0x00005597ae24bbe8
    id: 11931,
    hearing_type: "LegacyHearing",
    hearing_id: 107249,
    hearing_task_id: 233530>],
 "88564-LegacyHearing"=>
  [#<HearingTaskAssociation:0x00005597ab4233d8
    id: 1295,
    hearing_type: "LegacyHearing",
    hearing_id: 88564,
    hearing_task_id: 53640>,
   #<HearingTaskAssociation:0x00005597ade4b5c0
    id: 3628,
    hearing_type: "LegacyHearing",
    hearing_id: 88564,
    hearing_task_id: 153190>],
 "88855-LegacyHearing"=>
  [#<HearingTaskAssociation:0x00005597ae803e00
    id: 1447,
    hearing_type: "LegacyHearing",
    hearing_id: 88855,
    hearing_task_id: 135161>,
   #<HearingTaskAssociation:0x00005597ae517ea8
    id: 1990,
    hearing_type: "LegacyHearing",
    hearing_id: 88855,
    hearing_task_id: 143049>],
 "89592-LegacyHearing"=>
  [#<HearingTaskAssociation:0x00005597ae5c45e0
    id: 5473,
    hearing_type: "LegacyHearing",
    hearing_id: 89592,
    hearing_task_id: 171085>,
   #<HearingTaskAssociation:0x00005597ae555028
    id: 1957,
    hearing_type: "LegacyHearing",
    hearing_id: 89592,
    hearing_task_id: 61020>],
 "89601-LegacyHearing"=>
  [#<HearingTaskAssociation:0x00005597ae537a78
    id: 1962,
    hearing_type: "LegacyHearing",
    hearing_id: 89601,
    hearing_task_id: 142904>,
   #<HearingTaskAssociation:0x00005597ae5378e8
    id: 1963,
    hearing_type: "LegacyHearing",
    hearing_id: 89601,
    hearing_task_id: 142909>],
 "94618-LegacyHearing"=>
  [#<HearingTaskAssociation:0x00005597ae4bb928
    id: 4883,
    hearing_type: "LegacyHearing",
    hearing_id: 94618,
    hearing_task_id: 166147>,
   #<HearingTaskAssociation:0x00005597add8dc78
    id: 4282,
    hearing_type: "LegacyHearing",
    hearing_id: 94618,
    hearing_task_id: 161947>],
 "112661-LegacyHearing"=>
  [#<HearingTaskAssociation:0x00005597ae27d4e0
    id: 12113,
    hearing_type: "LegacyHearing",
    hearing_id: 112661,
    hearing_task_id: 243038>,
   #<HearingTaskAssociation:0x00005597ae28d2c8
    id: 12112,
    hearing_type: "LegacyHearing",
    hearing_id: 112661,
    hearing_task_id: 242008>],
 "112616-LegacyHearing"=>
  [#<HearingTaskAssociation:0x00005597ae23efd8
    id: 12092,
    hearing_type: "LegacyHearing",
    hearing_id: 112616,
    hearing_task_id: 234037>,
   #<HearingTaskAssociation:0x00005597ae209b80
    id: 12093,
    hearing_type: "LegacyHearing",
    hearing_id: 112616,
    hearing_task_id: 242675>],
 "92199-LegacyHearing"=>
  [#<HearingTaskAssociation:0x00005597adf93158
    id: 3170,
    hearing_type: "LegacyHearing",
    hearing_id: 92199,
    hearing_task_id: 39563>,
   #<HearingTaskAssociation:0x00005597adda8ca8
    id: 4255,
    hearing_type: "LegacyHearing",
    hearing_id: 92199,
    hearing_task_id: 160628>]}
```

**Comment by tomas-nava** [comment]
Oh, whoops. My constraint checks for identical `hearing_type`, `hearing_id`, AND `hearing_task_id`. It should just care about the first two. I will refactor.

**Comment by tomas-nava** [comment]
I realized we're explicitly creating duplicate `HearingTask`s and `HearingTaskAssociation`s when we [create `ChangeHearingDisposition` tasks](https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/models/tasks/schedule_hearing_task.rb#L102). I believe that's the source of all the tasks below except for No. 16.

To accommodate that functionality, I removed the database constraint and made the validation on `HearingTaskAssociation` and the associations on `Hearing` and `LegacyHearing` explicit in allowing one *open* `HearingTask` to be associated with a hearing via a `HearingTaskAssociation`.

Even though No. 16 below is valid with this constraint, we should look more closely at it and make sure it's in an expected state.

```sql
SELECT
hta.hearing_type,
hta.hearing_id,
LISTAGG(hta.id, ', ') AS association_ids,
LISTAGG(hta.hearing_task_id, ', ') AS hearing_task_ids,
LISTAGG(ht.status, ', ') AS hearing_task_statuses,
COUNT(*) AS count
FROM hearing_task_associations hta
LEFT OUTER JOIN tasks ht ON hta.hearing_task_id = ht.id
GROUP BY hta.hearing_type, hta.hearing_id
HAVING count > 1
ORDER BY hta.hearing_id;
```

| | hearing_id | association_ids | hearing_task_ids | hearing_task_statuses | count |
| --- | --- | --- | --- | --- | --- |
| 1 | 84987 | 54, 10162 | 41092, 215773 | cancelled, cancelled | 2 |
| 2 | 87462 | 5843, 928 | 163668, 42598 | completed, cancelled | 2 |
| 3 | 87522 | 937, 10329 | 69793, 218776 | cancelled, cancelled | 2 |
| 4 | 88564 | 1295, 3628 | 53640, 153190 | cancelled, completed | 2 |
| 5 | 88855 | 1447, 1990 | 135161, 143049 | cancelled, cancelled | 2 |
| 6 | 89592 | 1957, 5473 | 61020, 171085 | cancelled, completed | 2 |
| 7 | 89601 | 1963, 1962 | 142909, 142904 | cancelled, cancelled | 2 |
| 8 | 92199 | 3170, 4255 | 39563, 160628 | cancelled, cancelled | 2 |
| 9 | 94618 | 4883, 4282 | 166147, 161947 | cancelled, cancelled | 2 |
| 10 | 95069 | 4447, 4448 | 107538, 163361 | cancelled, completed | 2 |
| 11 | 95528 | 12282, 4678 | 248758, 44061 | on_hold, cancelled | 2 |
| 12 | 96593 | 5137, 12214 | 56800, 246659 | cancelled, on_hold | 2 |
| 13 | 96710 | 5178, 10942 | 107998, 227802 | cancelled, completed | 2 |
| 14 | 99981 | 6724, 10788 | 127454, 225016 | cancelled, cancelled | 2 |
| 15 | 101424 | 10916, 7354 | 227596, 40889 | cancelled, cancelled | 2 |
| 16 | 107249 | 11931, 9774 | 233530, 212325 | on_hold, completed | 2 |
| 17 | 110215 | 11170, 12119 | 45962, 243132 | cancelled, on_hold | 2 |
| 18 | 112616 | 12093, 12092 | 242675, 234037 | on_hold, cancelled | 2 |
| 19 | 112661 | 12113, 12112 | 243038, 242008 | on_hold, cancelled | 2 |
| 20 | 112803 | 12186, 12132 | 246284, 119573 | on_hold, cancelled | 2 |

**Comment by tomas-nava** [comment]
In the course of researching this PR we found `HearingTask` 142909 on `LegacyAppeal` 203129  associated with wrong `LegacyHearing` 89601, probably due to the bug fixed with #11144. I ran this command to fix the assocation:

```ruby
HearingTaskAssociation.find_by(hearing_task_id: 142909).update(hearing_id: 89597)
```

**Pull request merged**
