### PR TITLE
Sign & Certify | Remove no longer needed questions and propagate information to PDF (formerly eForm8)

### PR DESCRIPTION
**Pull request by ariperez-gov**

### CODE REVIEW

**Comment by ariperez-gov** [comment]
Here it goes with not yet hooked up Props.  I'm more than willing to jump back on this story when Redux is in place so that I can finish it up.  Great learning experience.

**Comment by ariperez-gov** [comment]
Connects to #1115

**Comment by amprokop** [comment]
sweet! @ariperez-gov would you mind adding a screenshot to the description? we find it helps the reviewer a lot with quickly getting context on a PR

**Comment by ariperez-gov** [comment]
image

**Comment by ariperez-gov** [comment]
sounds good! Ping me when React is in place!

**Pull request merged**
