### PR TITLE
Form 9A should toggle visibility of 9B closes #585

### LINKED ISSUE #585: Question 9B should only be shown if 9A == 'no'
1) go to form 8 page.
2) Select "Service Organization" for question 8A
3) Select "Yes" for question 9A
4) Write something in 9B
5) submit the form.

Whatever you wrote down in 9B does not appear on the form. I assume that's because it's irrelevant (with an answer of yes on 9A).

Should we just hide 9B when 9A is yes, instead of blowing out the user's input?

### PR DESCRIPTION
**Pull request by orischwartz**

### CODE REVIEW

**Comment by shanear** [comment]
The logic here is reversed. Yes should hide the field, no should show it.

**Comment by orischwartz** [comment]
Good catch. 

* `showthese` and `hidethese` attributes for 9A options have been reversed
* title of #585 updated.

**Comment by shanear** [comment]
also merge master in

**Comment by shanear** [comment]
solid. will merge in when it's in sync with master.

**Pull request merged**
