### PR TITLE
Adding the new version of Form 8

### PR DESCRIPTION
**Pull request by sharonwarner**
This PR adds a Form8_v2 feature toggle for Certification V2. 

Connects #1715 

- [x] Form8_v2 is correctly filled out
- [x] Form8_v1 is correctly filled out

screen shot 2017-05-08 at 4 50 32 pm
screen shot 2017-05-08 at 4 51 38 pm

### CODE REVIEW

**Comment by amprokop** [comment]
LGTM, great job on this

**Comment by amprokop** [comment]
Can you make an issue to remove the form8 v1 code when we're done rolling it out, and link to this PR in it and add a short description of what to do @sharonwarner

**Comment by amprokop** [comment]
Thanks!

**Comment by sharonwarner** [comment]
https://github.com/department-of-veterans-affairs/caseflow/issues/1933

Issue for removing old form8 when we're done with it.

**Pull request merged**
