### PR TITLE
No "Mark complete" action for SendCavcRemandProcessedLetterTask that is assigned to an org

### LINKED ISSUE #15898: Remove the "Mark complete" action for SendCavcRemandProcessedLetterTask assigned to an org
## Description
Remove the "Mark complete" action for `SendCavcRemandProcessedLetterTask` that is assigned to an org.
This will enforce assignment to a user prior to marking the send task complete.

## Acceptance criteria
- [ ] No "Mark complete" action for `SendCavcRemandProcessedLetterTask` that is assigned to an org
- [ ] "Mark complete" action for `SendCavcRemandProcessedLetterTask` that is assigned to a user

## Background/context/resources
[Slack](https://dsva.slack.com/archives/CJL810329/p1612825580210900)

### PR DESCRIPTION
**Pull request by yoomlam**
Resolves #15898

### Description
Remove the "Mark complete" action for SendCavcRemandProcessedLetterTask assigned to an org

### Acceptance Criteria
- [ ] No "Mark complete" action for `SendCavcRemandProcessedLetterTask` that is assigned to an org
- [ ] "Mark complete" action for `SendCavcRemandProcessedLetterTask` that is assigned to a user

### Testing Plan

1. Login as a CAVC lit support user
2. Go to http://localhost:3000/organizations/cavc-lit-support?tab=unassignedTab
3. Select an appeal with "Send CAVC-Remand-Processed Letter Task" to view the Case Details page. Note the docket number and UUID so you can find this appeal later.
4. Note that "Mark as complete" is not an available task action. Select "Assign to person". Select some user, possibly yourself. If you choose another user, log in as that other user.
5. Go to Case Details for the case you just modified.
7. Check the task tree.
6. Select "Mark as complete" and submit.
7. Check the task tree.  Play around and stress test.

### User Facing Changes
 - [ ] Screenshots of UI changes

 BEFORE|AFTER
 ---|---
image | image

### CODE REVIEW

**Comment by yoomlam** [comment]
Did not write new tests since these capture the desired behavior:
https://github.com/department-of-veterans-affairs/caseflow/blob/7b537d9896b3bd85aeeda11c4c3d194a04ad8fc1/spec/models/tasks/send_cavc_remand_processed_letter_task_spec.rb#L88

https://github.com/department-of-veterans-affairs/caseflow/blob/7b537d9896b3bd85aeeda11c4c3d194a04ad8fc1/spec/models/tasks/send_cavc_remand_processed_letter_task_spec.rb#L103

**Comment by araposo-tistatech** [comment]
PM Reviewed and accepted

**Review by jcq — APPROVED** [review]
Very straightforward, and worked fine in manual testing

Is it worth adding any automated tests to verify available task actions like this?

**Comment by yoomlam** [comment]
> Very straightforward, and worked fine in manual testing
> 
> Is it worth adding any automated tests to verify available task actions like this?

There are tests. The tests refer to the constants so they don't need to change.

**Pull request merged**
