### PR TITLE
Fixes #223 -- added a small animation on showing/hiding fields.

### LINKED ISSUE #223: Add transition fade in/out for hidden/unhidden fields
This will add more visual queueing for users to know when a field is appearing or disappearing.

Examples where there are no transitions:

### PR DESCRIPTION
**Pull request by alex**
Also a small JS cleanup.

### CODE REVIEW

**Comment by webinista** [comment]
This breaks the modal.

**Comment by alex** [comment]
Doh. will investigate.

**Comment by alex** [comment]
Works now. I don't love the animation on the fly in though. Thoughts?

**Comment by paultag** [comment]
Assigning @webinista for review. Also might be worth CC'ing @KHarshawat

**Comment by webinista** [comment]
Holding off on reviewing/merging this until #332 is merged. That may have ripple effects for this PR.

**Comment by alex** [comment]
@webinista :+1:

**Comment by plusjeff** [comment]
@webinista Merged #453 fo #332 , but that has caused merge conflicts. Will assign to you for merge fixing, but assign to @KHarshawat for design review after that's complete.

**Comment by alex** [comment]
Merge conflict resolved!

**Comment by webinista** [comment]
Punting to @plusjeff. Adjusted some of the JavaScript and HTML to resolve conflicts between this branch and master. Probably not the best person to review this anymore.

The closing animation looks funky as does the modal's opening. From a technical POV, I think this is okay to merge. From a user experience POV, we can do better.

**Comment by alex** [comment]
If there's any cconcrete suggestions for how to improve teh UX, I'm happy to.

**Comment by webinista** [comment]
Animating the height of the container for each parent is a better way to go. 

As it is now —at least in Chrome — the input element ends up shrinking first before being hidden. It works, but looks weird.

**Pull request merged**
