### PR TITLE
Refactored searchable dropdown to use appropriate aria roles

### PR DESCRIPTION
**Pull request by sahalliburton**
Resolves [CASEFLOW-1012](https://vajira.max.gov/browse/CASEFLOW-1012)

Part 1 of the [508 compliance stack](https://github.com/department-of-veterans-affairs/caseflow/pull/16374)

### Description
Resolves the issue where JAWS was reading the word "Edit" after reading the label for a searchable dropdown

### Acceptance Criteria
- [ ] Code compiles correctly
- [ ] JAWS no longer reads the word "edit" after focusing the Docket Type searchable dropdown in the add hearing day form

### Testing Plan
1. First setup your environment to use JAWS following [these steps](https://github.com/department-of-veterans-affairs/appeals-team/blob/master/Engineering/accessibility-jaws-setup.md)
2. Once you are at the screen to select a user, choose `BVASYELLOW` and navigate to the hearings schedule: http://10.0.2.2:3000/hearings/schedule
3. Click the "Add Hearing Day" link
4. Click on the Docket Type label so that JAWS will read the label and ensure that it does not announce the word "edit" after announcing the label

### CODE REVIEW

**Review by tomas-nava — APPROVED** [review]
Confirmed in JAWS that it used to read "Type of Docket **Edit** Combo Collapsed" and now reads "Type of Docket Listbox Collapsed Has Popup".

If the failing JS tests are related to your change they'll need to be addressed before this is ready to merge, otherwise, looks good to me.

**Comment by meckila-navapbc** [comment]
Taking a look at the tests, the axe error "ARIA role listbox is not allowed for given element" likely stems from the fact that the input can't have a "listbox" role. It appears that the aria 1.0 specification does, however, [allow an input to have the role "combobox"](https://www.w3.org/TR/wai-aria-practices-1.1/examples/combobox/aria1.0pattern/combobox-autocomplete-both.html). This is according to the [1.1 spec](https://www.w3.org/TR/wai-aria-1.1/#combobox). The first box has the "combobox" role on the input upon inspection.

JAWS still read the edit portion, so I'm not sure how/if it can be omitted. The AC from the JIRA ticket says it should read as a "combobox", correct?

**Comment by sahalliburton** [comment]
> Taking a look at the tests, the axe error "ARIA role listbox is not allowed for given element" likely stems from the fact that the input can't have a "listbox" role. It appears that the aria 1.0 specification does, however, [allow an input to have the role "combobox"](https://www.w3.org/TR/wai-aria-practices-1.1/examples/combobox/aria1.0pattern/combobox-autocomplete-both.html). This is according to the [1.1 spec](https://www.w3.org/TR/wai-aria-1.1/#combobox). The first box has the "combobox" role on the input upon inspection.
> 
> JAWS still read the edit portion, so I'm not sure how/if it can be omitted. The AC from the JIRA ticket says it should read as a "combobox", correct?

This issue from the ticket is actually to prevent JAWS from reading the word "edit", however as you mentioned this seems to be expected behavior based on WCAG guidance

**Review by tomas-nava — CHANGES_REQUESTED** [review]
Reversing my approval after the comments above and a conversation with @lund5000 and @sahalliburton ... we will raise our questions about this issue with the 508 team next week.

**Pull request closed without merging**
