### PR TITLE
Fixes #543, translates form 8A radio values back to their label before populating PDF

### LINKED ISSUE #543: "APPELLANT REPRESENTED IN THIS APPEAL BY" is completed incorrectly
screen shot 2016-01-21 at 11 01 34 am

### PR DESCRIPTION
**Pull request by orischwartz**

### CODE REVIEW

**Comment by webinista** [comment]
Initial check looks good, and doesn't break anything on the front end. I can't verify output because PDFTK doesn't work so well on Yosemite.

**Comment by orischwartz** [comment]
@shanear can you review/verify this? Generated PDF should be populated with label text for field 8A instead of the upper-underscore-formatted value.

**Comment by shanear** [comment]
Sorry it took me so long to get to this, but I tested it out, and it's looking like it's still not working. Didn't dig too hard into why.

screen shot 2016-02-01 at 11 24 47 am

**Comment by orischwartz** [comment]
@shanear can you take another look at branch issue#543? Small fix since this pull. I think it's a more maintainable approach than the if/else sequence.

**Comment by shanear** [comment]
@orischwartz yeah, can you merge master in?

**Comment by orischwartz** [comment]
Do not test yet, this obviously conflicts with pull #578, need an additional commit here to revert that change.

**Comment by orischwartz** [comment]
@shanear ok, ready to test now

**Pull request merged**
