### PR TITLE
Checks 'Other' box for question 13 if there is data in 'Specify Other' field

### LINKED ISSUE #343: If 13 "Other" has text, check "Other" on the question 13 checkboxen
Seems unintuitive to strip the contents if other isn't set, rather, other being full of text should set other

### PR DESCRIPTION
**Pull request by webinista**
closes #343

### CODE REVIEW

**Comment by paultag** [comment]
@webinista Mind also fixing the logic as it exists on the backend?

https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/controllers/web_controller.rb#L128-L130

**Comment by webinista** [comment]
This may be a question for @KHarshawat, but should unchecking other also clear the field?

**Comment by webinista** [comment]
Might

```
if fields['13_RECORDS_TO_BE_FORWARDED_TO_BOARD_OF_VETERANS_APPEALS_OTHER_REMARKS'] unless fields['13_RECORDS_TO_BE_FORWARDED_TO_BOARD_OF_VETERANS_APPEALS_OTHER_REMARKS'].blank?
```

be a good way to go here?

**Comment by paultag** [comment]
@webinista http://api.rubyonrails.org/classes/Object.html#method-i-blank-3F - it appears as though I'm super wrong and just `.blank?` should work

**Comment by paultag** [comment]
Re-reviewing the PR now :)

:+1:

**Comment by webinista** [comment]
:+1: thanks :-)

**Comment by paultag** [comment]
@webinista The logic is flipped -- the following diff worked for me locally --

```diff
diff --git a/app/controllers/web_controller.rb b/app/controllers/web_controller.rb
index c492d85..0800d10 100644
--- a/app/controllers/web_controller.rb
+++ b/app/controllers/web_controller.rb
@@ -125,7 +125,7 @@ class WebController < ApplicationController
       end
     end
 
-    if fields['13_RECORDS_TO_BE_FORWARDED_TO_BOARD_OF_VETERANS_APPEALS_OTHER_REMARKS'].blank?
+    if !fields['13_RECORDS_TO_BE_FORWARDED_TO_BOARD_OF_VETERANS_APPEALS_OTHER_REMARKS'].blank?
       fields['13_RECORDS_TO_BE_FORWARDED_TO_BOARD_OF_VETERANS_APPEALS_OTHER'] = true
     end
 
```

**Comment by paultag** [comment]
LGTM!

**Pull request merged**
