### PR TITLE
Issue#308 Adding 'documents found' message

### LINKED ISSUE #308: Show that documents were found on questions page
Add green wds confirmation tooltip that says that all documents were found in VBMS.

image

### PR DESCRIPTION
**Pull request by webinista**
Most of the files in this commit are new icon images. The changes to review are:

- app/assets/stylesheets/application.css.scss
- app/views/web/start.html.erb
- app/views/web/_documents_message.html.erb

Feel free to suggest a more efficient or idiomatic way to do this check. Screen shot below. closes #308 

screen shot 2015-12-04 at 10 05 00 pm

### CODE REVIEW

**Comment by paultag** [comment]
@webinista Should we move this to the questions page, rather than the mismach page?

**Comment by webinista** [comment]
@paultag Yes. Yes we should. Thanks for pointing that out.

**Comment by paultag** [comment]
:+1: on it

**Comment by paultag** [comment]
Looks good to me, ready to land, will merge!

**Pull request merged**
