### PR TITLE
Add NewRelic APM

### PR DESCRIPTION
**Pull request by nickheiner-usds**
Connects #3842.

It's alive! 

image

This is data from my local environment.

To make this work in deployed tiers, we'll need a PR to appeals-deployment to provide the NR license key as an env var.

### CODE REVIEW

**Comment by sunil-sadasivan** [comment]
Before deploying to prod... I just want to make sure @NickHeiner:  are you able to confirm the NR APM isn't logging the the request headers or environment variables for requests?  

I think specifically we'll want to ensure PII isn't stored

**Comment by nickheiner-usds** [comment]
:+1: investigating now.

**Comment by nickheiner-usds** [comment]
I do not believe that NewRelic stores environment variables.

1) When I enable auditing, `logs/newrelic_audit.log`, which purports to show all data that the agent is reporting, does not include env vars.
1) [High Security Mode](https://docs.newrelic.com/docs/agents/manage-apm-agents/configuration/high-security-mode) does not make any mention of omitting env var capture, and if it were a thing that existed, you'd think High Security Mode would disable it.
1) I can't find anywhere in the UI that displays them, including the [Environment](https://rpm.newrelic.com/accounts/1788458/applications/80542875/environment) page.
1) Googling does not suggest it's a thing NR does.

**Comment by nickheiner-usds** [comment]
I see queries being reported to NewRelic:

```rb
"SELECT  \"appeal_views\".* FROM \"appeal_views\" WHERE \"appeal_views\".\"appeal_id\" = $? AND \"appeal_views\".\"user_id\" = $? LIMIT ?"
```

It does not report the values that fill in the `?` placeholders. As long as we continue to use ActiveRecord and don't write raw SQL queries that don't use argument placeholders, we'll be safe. Failing to use argument placeholders is a massive security problem anyway, so I think we can trust that we'll avoid doing that.

**Comment by nickheiner-usds** [comment]
> How does high security mode get turned on... is that a configuration within NewRelic project settings?

[The docs](https://docs.newrelic.com/docs/agents/manage-apm-agents/configuration/high-security-mode) make it sound straightforward to active, but once we turn it on, we can't turn it back off without human intervention from a NR employee. So I'm going to try to piecemeal-disable stuff first, before we try high security mode.

**Comment by nickheiner-usds** [comment]
I've enabled HTTP header whitelisting to only log known headers that do not contain PII. It seems very unlikely that we'd decide to clobber the `user-agent` header and put an SSN in it, for instance.

**Pull request merged**
