### PR TITLE
Disable save button when submitting changes to AOD

### PR DESCRIPTION
**Pull request by ferristseng**
https://dsva.slack.com/archives/C3EAF3Q15/p1596044684201800

Related to https://github.com/department-of-veterans-affairs/dsva-vacols/issues/128

### Description

We are seeing duplicate AOD records in production. Some of these look like they are related to double submitting a form from the timestamps of when they were created.

### Test Plan

1. Login as BVAAABSHIRE
2. Navigate to a docket with hearings
3. Change the AOD to "Granted", and the AOD reason to anything
4. Click the save button as many times as possible, **it should be disabled after the first time you click it**
5. Ensure that only one success message displays

### CODE REVIEW

**Comment by nanotone** [comment]
@ferristseng Since this PR doesn't update any tests (our feature tests typically only cover happy-path anyway) could you write up a quick Testing Plan so the repro is clear?

**Comment by ferristseng** [comment]
> @ferristseng Since this PR doesn't update any tests (our feature tests typically only cover happy-path anyway) could you write up a quick Testing Plan so the repro is clear?

@nanotone Done!

**Comment by nanotone** [comment]
Interestingly, on an un-fixed branch I was able to repro multiple XHRs easily (see screenshot), but it never created multiple AOD records. However, I believe that's only because the dev Rails server is single-threaded (and single-process of course), in which case the dupe record race condition would certainly still be worth fixing for prod.

**Comment by ferristseng** [comment]
I think the logic for "upserting" was changed in this PR here, which partially fixed the duplicate issue:

https://github.com/department-of-veterans-affairs/caseflow/pull/14102/files#diff-5d9e30dee5f616f6cfc5a7034a62db07R30-R32

_but_, the issue should effect AOD records where the reason is `age` (because of the `eligible_due_to_date` scope). You should still be able to reproduce the issue if you set the reason to `age` on an unfixed branch.

**Comment by nanotone** [comment]
@ferristseng You're absolutely right, it repro'd with `age`.

**Comment by yoomlam** [comment]
@ferristseng Are you planning to fix the duplicates in the prod DB?

**Comment by ferristseng** [comment]
@yoomlam I wasn't, but we can make a ticket for it.

**Pull request merged**
