### PR TITLE
Adding `style="pointer-events:none;"` to inline SVG. closes #412

### LINKED ISSUE #412: Add style="pointer-events:none" to inline SVG
Needed to prevent them from getting `click` events when used as buttons.

### PR DESCRIPTION
**Pull request by webinista**
Prevents SVG elements from intercepting mouse events. Applying to the SVG directly instead of via CSS just in case someone tries using Caseflow with IE9 or IE10 (which don't support `pointer-events:none` for HTML).

### CODE REVIEW

**Comment by alex** [comment]
Can you explain why `pointer-events: none` is needed? I'm not sure I understand what happens if we don't use this.

**Comment by webinista** [comment]
It's really only needed for the Copy to Clipboard and modal close button (#413). Happy to remove it from other places, but there's no harm caused by having it there.

Because the SVG is inline, it's part of the DOM. If the user clicks/taps on it, the SVG element will receive the mouse/touch event. The value of `event.target` and `event-currentTarget` will be the `path`, `stroke`, or `svg` root element clicked on instead of the button.

**Comment by alex** [comment]
Interesting, when I experimented with clicking on it, it appeared to still
copy the SSN as expected. Was there some other step I missed to reproduce
the issue?

On Thu, Dec 17, 2015 at 3:05 PM, Tiffany Brown <notifications@github.com>
wrote:

> It's really only needed for the Copy to Clipboard and modal close button (
> #413 <https://github.com/department-of-veterans-affairs/caseflow/pull/413>).
> Happy to remove it from other places, but there's no harm caused by having
> it there.
>
> Because the SVG is inline, it's part of the DOM. If the user clicks/taps
> on it, the SVG element will receive the mouse/touch event. The value of
> event.target and event-currentTarget will be the path, stroke, or svg
> root element clicked on instead of the button.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/department-of-veterans-affairs/caseflow/pull/415#issuecomment-165568044>
> .
>



-- 
"I disapprove of what you say, but I will defend to the death your right to
say it." -- Evelyn Beatrice Hall (summarizing Voltaire)
"The people's good is the highest law." -- Cicero
GPG Key fingerprint: 125F 5C67 DFE9 4084

**Comment by webinista** [comment]
Nope. Entirely possible that it's not needed there because Clipboard.js handles things correctly. I added it more as a precaution, since I never tested clicking directly on the SVG icon. 

If clicking on the SVG icon doesn't cause problems with the clipboard button, I'll close this PR.

**Pull request closed without merging**
