### PR TITLE
Rename available actions dropdown on task

### PR DESCRIPTION
**Pull request by leikkisa**
Resolves [CASEFLOW-1222](https://vajira.max.gov/browse/CASEFLOW-1222)

### Description
The options are being read as expected, most likely due to other 508 fixes on the searchable dropdown. However, there was one name being read that was reading the appeal's UUID so that has been renamed.

### Acceptance Criteria
- [ ] Docket-switch related options are read in the searchable dropdowns

### Testing Plan
1. Test adding Docket Switch Task, Send Docket Switch to Judge, Rule on Docket Switch, Complete Docket Switch in JAWS

### CODE REVIEW

**Comment by leikkisa** [comment]
Before Jaws (for available actions, reading out the UUID, option readout working):

```
Case Details | Caseflow - Google Chrome 
MainRegion 
MainRegion 
Link View 19 docs
Case Details | Caseflow - Google Chrome
heading level 2 Button + Add a new task
To activate press Enter.
list 
with 3 items
View task instructions Button 

* Activated task action dropdown *
To activate press Enter.
start-checkout-flow-45cfc460-420a-4f35-96b4-27e977bbb89e-4095 edit combo collapsed
To set the value use the Arrow keys or type the value.
expanded
 option Change task type focused, 1 of 7. 7 results available. Use Up and Down to choose options, press Enter to select the currently focused option, press Escape to exit the menu, press Tab to select the option and exit the menu.
 option Assign to team focused, 2 of 7. 7 results available. Use Up and Down to choose options, press Enter to select the currently focused option, press Escape to exit the menu, press Tab to select the option and exit the menu.
 option Re-assign to person focused, 3 of 7. 7 results available. Use Up and Down to choose options, press Enter to select the currently focused option, press Escape to exit the menu, press Tab to select the option and exit the menu.
 option Put task on hold focused, 4 of 7. 7 results available. Use Up and Down to choose options, press Enter to select the currently focused option, press Escape to exit the menu, press Tab to select the option and exit the menu.
 option Mark task complete focused, 5 of 7. 7 results available. Use Up and Down to choose options, press Enter to select the currently focused option, press Escape to exit the menu, press Tab to select the option and exit the menu.
 option Cancel task focused, 6 of 7. 7 results available. Use Up and Down to choose options, press Enter to select the currently focused option, press Escape to exit the menu, press Tab to select the option and exit the menu.
 option Send to Judge focused, 7 of 7. 7 results available. Use Up and Down to choose options, press Enter to select the currently focused option, press Escape to exit the menu, press Tab to select the option and exit the menu.
 option Change task type focused, 1 of 7. 7 results available. Use Up and Down to choose options, press Enter to select the currently focused option, press Escape to exit the menu, press Tab to select the option and exit the menu.
 option Assign to team focused, 2 of 7. 7 results available. Use Up and Down to choose options, press Enter to select the currently focused option, press Escape to exit the menu, press Tab to select the option and exit the menu.
 option Re-assign to person focused, 3 of 7. 7 results available. Use Up and Down to choose options, press Enter to select the currently focused option, press Escape to exit the menu, press Tab to select the option and exit the menu.
 option Put task on hold focused, 4 of 7. 7 results available. Use Up and Down to choose options, press Enter to select the currently focused option, press Escape to exit the menu, press Tab to select the option and exit the menu.
 option Mark task complete focused, 5 of 7. 7 results available. Use Up and Down to choose options, press Enter to select the currently focused option, press Escape to exit the menu, press Tab to select the option and exit the menu.
 option Cancel task focused, 6 of 7. 7 results available. Use Up and Down to choose options, press Enter to select the currently focused option, press Escape to exit the menu, press Tab to select the option and exit the menu.
 option Send to Judge focused, 7 of 7. 7 results available. Use Up and Down to choose options, press Enter to select the currently focused option, press Escape to exit the menu, press Tab to select the option and exit the menu.
```

**Comment by leikkisa** [comment]
This is the docket switch mail task readout (it is repeated a few times because I was testing the search function):
```
Case Details | Caseflow - Google Chrome
heading level 2 Button + Add a new task
To activate press Enter.
Correspondence type selector edit combo expanded 

To set the value use the Arrow keys or type the value.
  option CAVC Correspondence focused, 1 of 20. 13 results available for search term d. Use Up and Down to choose options, press Enter to select the currently focused option, press Escape to exit the menu, press Tab to select the option and exit the menu.
  option Docket Switch focused, 7 of 20. 2 results available for search term do. Use Up and Down to choose options, press Enter to select the currently focused option, press Escape to exit the menu, press Tab to select the option and exit the menu.
  option Docket Switch focused, 7 of 20. 2 results available for search term doc. Use Up and Down to choose options, press Enter to select the currently focused option, press Escape to exit the menu, press Tab to select the option and exit the menu.
  option Docket Switch focused, 7 of 20. 2 results available for search term dock. Use Up and Down to choose options, press Enter to select the currently focused option, press Escape to exit the menu, press Tab to select the option and exit the menu.
  option Docket Switch focused, 7 of 20. 2 results available for search term docke. Use Up and Down to choose options, press Enter to select the currently focused option, press Escape to exit the menu, press Tab to select the option and exit the menu.
  option Docket Switch focused, 7 of 20. 2 results available for search term docket. Use Up and Down to choose options, press Enter to select the currently focused option, press Escape to exit the menu, press Tab to select the option and exit the menu.
  0 results available. Select is focused ,type to refine list, press Down to open the menu,
collapsed 
 option Docket Switch, selected.
  option Docket Switch focused, 7 of 20. 20 results available. Use Up and Down to choose options, press Enter to select the currently focused option, press Escape to exit the menu, press Tab to select the option and exit the menu.
expanded 
  option Death certificate focused, 6 of 20. 20 results available. Use Up and Down to choose options, press Enter to select the currently focused option, press Escape to exit the menu, press Tab to select the option and exit the menu.
  option Docket Switch focused, 7 of 20. 20 results available. Use Up and Down to choose options, press Enter to select the currently focused option, press Escape to exit the menu, press Tab to select the option and exit the menu.
  option Death certificate focused, 6 of 20. 20 results available. Use Up and Down to choose options, press Enter to select the currently focused option, press Escape to exit the menu, press Tab to select the option and exit the menu.
```

**Comment by leikkisa** [comment]
Here's from the Rule on Docket Switch:
```
Search cases Link 
BVAKKEELING (VACO) same page link collapsed menu 
MainRegion 
MainRegion 
Copy Veteran ID 209179363 Button 
To activate press Enter.
Copy Veteran ID 209179363 Button 
To activate press Enter.
Direct Review 
View 19 docs Link 
 Mark this case as overtime Button 
To activate press Enter.
list 
with 3 items
View task instructions Button 
To activate press Enter.
Available actions edit combo collapsed 

To set the value use the Arrow keys or type the value.
  option Add admin action focused, 1 of 4. 4 results available. Use Up and Down to choose options, press Enter to select the currently focused option, press Escape to exit the menu, press Tab to select the option and exit the menu.
expanded 
  option Put task on hold focused, 2 of 4. 4 results available. Use Up and Down to choose options, press Enter to select the currently focused option, press Escape to exit the menu, press Tab to select the option and exit the menu.
  option Re-assign to a judge focused, 3 of 4. 4 results available. Use Up and Down to choose options, press Enter to select the currently focused option, press Escape to exit the menu, press Tab to select the option and exit the menu.
  option Rule on Docket Switch focused, 4 of 4. 4 results available. Use Up and Down to choose options, press Enter to select the currently focused option, press Escape to exit the menu, press Tab to select the option and exit the menu.
Rule on Docket Switch | Caseflow - Google Chrome
Case Details | Caseflow
MainRegion 
Rule on Docket Switch 
MainRegion 
How will you rule on this docket switch? group 
Grant all issues radio button checked 
1 of 3
Provide any additional context and instructions edit 
```

**Comment by leikkisa** [comment]
And here's from the Grant Docket Switch option:
```
Queue Link 
Search cases Link 
COB_USER (VACO) same page link collapsed menu 
MainRegion 
MainRegion 
Copy Veteran ID 209179363 Button 
To activate press Enter.
Copy Veteran ID 209179363 Button 
To activate press Enter.
Direct Review 
View 19 docs Link 
+ Add a new task heading level 2 Button 
To activate press Enter.
list 
with 3 items
View task instructions Button 
To activate press Enter.
Available actions edit combo collapsed 

To set the value use the Arrow keys or type the value.
  option Add admin action focused, 1 of 3. 3 results available. Use Up and Down to choose options, press Enter to select the currently focused option, press Escape to exit the menu, press Tab to select the option and exit the menu.
expanded 
  option Cancel task and return to judge focused, 2 of 3. 3 results available. Use Up and Down to choose options, press Enter to select the currently focused option, press Escape to exit the menu, press Tab to select the option and exit the menu.
  option Grant Docket Switch focused, 3 of 3. 3 results available. Use Up and Down to choose options, press Enter to select the currently focused option, press Escape to exit the menu, press Tab to select the option and exit the menu.
Grant Docket Switch | Caseflow - Google Chrome
```

**Review by nanotone — APPROVED** [review]
This looks good! Feel free to merge, but I have one non-blocking question -- was there any code that was expecting the appeal & task to be in the SearchableDropdown `name` rather than `id`? Since the feature tests all pass, I'm guessing not.

**Pull request merged**
