### PR TITLE
Adding conditional show/hide for Form 8. closes #332

### LINKED ISSUE #332: Bring back hidden form fields

### PR DESCRIPTION
**Pull request by webinista**
- Changes the way the required class is added to text fields
- Fixed a regression in questions 5 - 7
- Adding conditional show/hide for 13: Specify Other field.
- Changing model for question 13.
- Adjusting style of .required class and its children.
- Making the question_num variable options.

### CODE REVIEW

**Comment by plusjeff** [comment]
For #332 (adding a mention link)

**Comment by plusjeff** [comment]
@webinista Sorry :cry: -- merge conflict. Can you merge and then assign back to me?

**Comment by webinista** [comment]
Also closes #219 when merged.

**Comment by plusjeff** [comment]
Testing the following, per #332:

- [ ] 5A/6A/7A (If these have content show 5B/6B/7B respectively)
- [ ] 5B/6B/7B (required if shown)
- [ ] 8A-9B

**Comment by plusjeff** [comment]
5A/6A/7A unhiding of corresponding xB fields, fails.

**Comment by plusjeff** [comment]
@webinista Some bugs from testing. Please assign back to me when all set for re-testing.

- [ ] 5A/6A/7A hide/unhide of xB fields
- [ ] 5,6,7B fields not testable ^^^
- [ ] 8A when choosing between options, doesn't clear values from re-hidden fields (example: 8A POA chosen, 8B displayed, 8A Agent chosen, 8B value still gets into form 8) Includes 8B, 8C, 9A, 9B.
- [ ] 10B doesn't hide/unhide 10C (this might be a missing condition from #332)
- [ ] 10A choosing no does not clear 10B, 10C values if previously entered (when visible)
- [ ] 13/Other unselected does not clear text box entry if value is previously entered (when visible)

For the ones that passed (checked in prior comment), it's because the controller clears values prior to Form 8 generation with logic similar to that described in #332 . Solution could either be that, or using JS to clear values at hide/unhide time.

**Comment by webinista** [comment]
@plusjeff 

> For the ones that passed (checked in prior comment), it's because the controller clears values prior to Form 8 generation with logic similar to that described in #332 . Solution could either be that, or using JS to clear values at hide/unhide time.

I don't understand. The form show/hide action should be conditional, when the user changes input (or if the field has data when the page initially loads). Why would that have anything to do with the controller?

**Comment by webinista** [comment]
> 10B doesn't hide/unhide 10C (this might be a missing condition from #332)

I think the way it works is correct. 10B and 10C should be shown when 10A is _Yes_. That could be clearer, however. _Was the hearing held?_ is implicitly, not explicitly asked in 10C. As a result, 10C looks like it's dependent on the answer for 10B, but it isn't.

@KHarshawat @maryannbrody can you two weigh in here?

screen shot 2016-01-04 at 5 06 25 pm

**Comment by alex** [comment]
Merge conflicts here :-(

**Comment by KHarshawat** [comment]
@webinista if 10A is yes then we should show 10B and 10C. It sucks that 10B and 10C aren't related to one another, but both related to 10A which could be confusing. This is a problem inherent with the Form 8. I'm ok with the way it works currently. Also our employees are experts, and I expect them to know the difference.

**Comment by plusjeff** [comment]
@webinista More merge conflicts :crying_cat_face:  - assign me back (but also ping me when this is all set and I'll get this in so you don't keep getting stuck in merging limbo 'cause I'm slow -- sorry!).

**Comment by webinista** [comment]
Broke something with last merge/rebase.

**Comment by plusjeff** [comment]
@webinista Some bugs. Assign back to be when all set.

- [ ] 8C shows as No, even when checked as Yes
- [ ] 8B checkboxes don't populate
- [ ] 10B shows as No, even when checked as Yes

**Comment by alex** [comment]
There's also a merge conflict here :-(

**Comment by webinista** [comment]
Blocks #504

**Comment by plusjeff** [comment]
Merging with known bugs, documented in #504

**Pull request merged**
