### PR TITLE
Sso login

### LINKED ISSUE #23: Replace VACOLS RO login with SAML login
We have (what looks like) working creds for the dev environment!

### PR DESCRIPTION
**Pull request by alex**
Fixes #23

### CODE REVIEW

**Comment by alex** [comment]
What this does:

- There are now 2 logins, one SSO and the other the VACOLS credentials, this gives us user identity and RO. We'll pare that down to just SSOi in the future
- SSO is optional, since we only have that for the test env so far.

**Comment by paultag** [comment]
Looks great, do we have the remaining todo bits from the old PR?

**Comment by alex** [comment]
- [ ] Hopefully get those PRs landed (we can land without)
- [x] Figure out why some of the fields have empty data in the SAML
- [ ] Figure out how to do the "RO" checking we do right now.
- [ ] Figure out what to do about the non-dev environments until we have creds for them
- [ ] Figure out what to do about local developer environments.

**Comment by paultag** [comment]
LGTM, thanks!

**Pull request merged**
