### PR TITLE
Show AMA date in error if receipt date before AMA date

### PR DESCRIPTION
**Pull request by leikkisa**
connects #9516 

We might want to remove the feature flag altogether since AMA day has happened.

### CODE REVIEW

**Comment by pkarman** [comment]
the feature flag is still disabled in uat/prod because we ran into timing issues. I think it will go away eventually but not until those timing issues are resolved.

**Comment by Sjones352** [comment]
feature flag still disabled in UAT so until it is resolved, this is it.

screen shot 2019-03-06 at 9 11 18 pm

**Comment by leikkisa** [comment]
You should still be able to validate this, it's just that the date that shows up in the error message will be further in the past. Between this and the other ticket, I'm wondering if these just aren't deploying properly to UAT.

**Comment by Sjones352** [comment]
**PASSES IN UAT**
screen shot 2019-03-07 at 2 42 00 pm

**Pull request merged**
