### PR TITLE
Autosave failure message

### PR DESCRIPTION
**Pull request by sharonwarner**
Connects #3377 

The success message will be implemented in a later PR.

To test:
1. Go to the hearing worksheet
1. Update line 263 in Dockets.js so that the url is incorrect
1. Update a field in the hearing worksheet
1. Confirm the error message is displayed
1. Fix line 263 in Dockets.js
1. Confirm that the save goes through and the error message goes away

### CODE REVIEW

**Comment by tejans24** [comment]
screen shot 2018-05-04 at 12 53 44 pm

is retry supposed to look like a button or a link?

**Comment by tejans24** [comment]
screen shot 2018-05-04 at 12 56 54 pm

is this supposed to implement the connected alert as well or is that in another PR?

**Comment by sharonwarner** [comment]
Oh whoa, one of the merges from master broke that styling! Going through it with Nolawi now. 

And yes, we discussed this in standup yesterday, though I will add it to the ticket in a second. We're postponing the success message to prioritize some other tickets.

**Comment by tejans24** [comment]
screen shot 2018-05-04 at 2 09 28 pm

Another thing I noticed is that this change removes the AutoSave component from showing up. there is no gap between the header and the worksheet header

**Comment by sharonwarner** [comment]
The auto component is still showing up, it's displaying the alert. I could update it to include the bar as well, but I don't think it displays any useful information. I'll check with Lara and Annie.

**Pull request merged**
