### PR TITLE
[DONT MERGE YET] Error handling

### PR DESCRIPTION
**Pull request by webinista**
Adding basic form error handling, messages, and visual styles (mostly) from Web Design Standards. 

Now with Safari support, just in case!

### CODE REVIEW

**Comment by paultag** [comment]
Code seems good! Have a screenshot? Re-assigning to @KHarshawat

**Comment by webinista** [comment]
error-handling

**Comment by KHarshawat** [comment]
@webinista 

For most of the questions ```Oops! Looks like you missed one! Please select one of these options.```

17a ```Please enter the name of the Certifying Official (usually your name).```

17b ```Please enter the title of the Certifying Official (e.g. Decision Review Officer)```

WDYT?

**Comment by webinista** [comment]
@KHarshawat I like it!

**Comment by webinista** [comment]
Conflicts have to do with changes merged in #257 / commit `de9251b`.

**Comment by webinista** [comment]
This is going to take so much merging and conflict resolution that I may as well start over. Closing.

**Pull request closed without merging**
