### PR TITLE
Allow lit support team members to create mail tasks

### LINKED ISSUE #12935: Litigatation Support Team has lost ability to create tasks.
## Description

 The litigation team is [reporting that they have lost the ability to add tasks](https://dsva.slack.com/archives/CHX8FMP28/p1575663281058100). 

This ticket exists to re-enable this functionality. 

## Background/context/resources

 Lit Support reports that they lost this ability on 12/2 or 12/3.

### PR DESCRIPTION
**Pull request by hschallhorn**
Resolves #12935 and [this hoopla](https://dsva.slack.com/archives/CHX8FMP28/p1575663281058100)

### Description
Previously, some `LitigationSupport` members had the ability to create mail tasks for ama appeals. This was because they were (incorrectly) members of the `MailTeam`, members of which have this ability. Now that these lit support members have been (correctly) removed from the `MailTeam`, they still need this functionality. This PR allows any user in the `LitigationSupport` organization to create `MailTasks`

### CODE REVIEW

**Comment by hschallhorn** [comment]
@msj0nes did we ever get confirmation that enabling this for _all_ lit support users was the way to proceed?

**Comment by msj0nes** [comment]
@hschallhorn @jimruggiero give me some time on this one. The team lead for Mail team was unaware that Litigation support team was sharing team functions and they are against it. 

**Reasons Provided:** 
- They don't want their department based reporting impacted by members of another team
- They were never told that this was a 'thing' and they would like to know why Lit support cant work within their own queue. 

Next Steps I'll Take:
Contacting Nina Dipadova (Lit Support Team Lead) to discuss the option of giving this functionality to all versus just a few members of lit support.

**Comment by jimruggiero** [comment]
Martina - please take this directly to Allison for further guidance. I
don’t think it’s all. I think it’s just Jasmine.

**Comment by msj0nes** [comment]
Will do Jim.

Regards,
Martina Jones
________________________________

**Pull request merged**
