### PR TITLE
BUG: Receipt Date of Docket Switch on Docket Switch Confirmation Page Incorrect

### PR DESCRIPTION
**Pull request by Sjones352**
Connects https://vajira.max.gov/browse/CASEFLOW-1261

### Description
When processing the docket switch as the COB user, the receipt date entered changed on the confirmation page for all of the docket switches I processed today.  As indicated in the snips below, I entered the docket switch receipt date as “3/26/2021” on the first page; however, on the confirmation page, the date reverted to “3/25/2021,” which was the date of receipt of the VA Form 10182 for all of these appeals.

### Acceptance Criteria
- [x] docketSwitchReceiptDate shows the receipt date entered changed on the confirmation page

### User Facing Changes
 
Screen Shot 2021-03-29 at 2 34 47 PM
Screen Shot 2021-03-29 at 2 35 33 PM

### CODE REVIEW

**Review by nanotone — COMMENTED** [review]
Nice and easy fix! 😸 

Do you wanna add a test for this? Since this spans multiple screens in the DS flow, the feature test might be a good place for that. For example, in the granted flow, the receipt date gets input [here](https://github.com/department-of-veterans-affairs/caseflow/blob/master/spec/feature/queue/docket_switch_spec.rb#L312) and could be verified on the confirmation page [here](https://github.com/department-of-veterans-affairs/caseflow/blob/master/spec/feature/queue/docket_switch_spec.rb#L348).

**Comment by Sjones352** [comment]
> Nice and easy fix! 😸
> 
> Do you wanna add a test for this? Since this spans multiple screens in the DS flow, the feature test might be a good place for that. For example, in the granted flow, the receipt date gets input [here](https://github.com/department-of-veterans-affairs/caseflow/blob/master/spec/feature/queue/docket_switch_spec.rb#L312) and could be verified on the confirmation page [here](https://github.com/department-of-veterans-affairs/caseflow/blob/master/spec/feature/queue/docket_switch_spec.rb#L348).

**Comment by Sjones352** [comment]
@nanotone this is ready for another review

**Review by nanotone — APPROVED** [review]
Nice, LGTM :shipit:

**Pull request merged**
