### PR TITLE
[DONT MERGE YET] Fix for linked fields bug, questions 11A/B bug

### PR DESCRIPTION
**Pull request by webinista**
- Also changes `text=text` to `type=text`, closing 227
- Corrects misspelling of _credentials_
- Checks that checkbox only toggles when the `data-showwhen` value is correct.

### CODE REVIEW

**Comment by plusjeff** [comment]
@webinista Can you sync with `master`? After that, assign back to me for review.

**Comment by webinista** [comment]
@plusjeff Are we folding the show/hide feature back in yet?

**Comment by paultag** [comment]
Consensus was no in the short term, yes in the long term. Mockups inbound with an idea on how to tweak the UI to make it a bit more solid to the user

**Comment by webinista** [comment]
Closing this because I'm pretty sure all of the logic needs to change.

**Pull request closed without merging**
