### PR TITLE
Cache finalized decision issues before receipt date on instance

### PR DESCRIPTION
**Pull request by nanotone**
Related to the 🦇 issue in #14472:
- [🦇 thread](https://dsva.slack.com/archives/CHX8FMP28/p1591277936051900)
- [🦊 thread](https://dsva.slack.com/archives/C54QCEHAL/p1591281463495000)

### Description
The SupplementalClaim in question was also taking forever to calculate and serialize contestable issues -- over 1 minute.

- It turns out that it has 423 contestable rating issues or decisions.
- For each of these, the `ContestableIssueGenerator` checks for a decision issue duplicate by calling back to the SC for prior finalized decision issues.
- The SC as 27 potential issues to check, each of which loads _its_ own SC (via `approx_decision_date`). None of these are cached.

All in all, the contestable issues serializer was hitting the DB about 10k extra times.

### Acceptance Criteria
- [ ] Code compiles correctly
- [ ] Manually tested by patching in Rails console and rerunning `sc.contestable_issues` -- elapsed time dropped to about 1 second.

### CODE REVIEW

**Comment by nanotone** [comment]
I also wanted to try DRYing up the implementations between Appeal and ClaimReview, because the only difference is that the CR filters by benefit_type.

But, I couldn't come up with a good name for that wide net of initial DecisionIssues (so that they can be pulled into a smaller polymorphic method). `related_decision_issues`?

**Comment by jcq** [comment]
I agree re trying to DRY out the code, but not coming up with good ideas for naming. Hopefully @leikkisa will weigh in. :)

**Comment by nanotone** [comment]
@leikkisa Sorry if this was unclear -- I'm looking to name the method that will be implemented as
- `DecisionIssue.where(participant_id: veteran.participant_id)` for appeals, and
- `DecisionIssue.where(participant_id: veteran.participant_id, benefit_type: benefit_type)` for claim reviews

Not sure if `business_line_decision_issues` would be suitable for the appeal side?

**Comment by nanotone** [comment]
Since this was for a 🦇 issue with no work-around, I'll merge now and follow-up with another PR.

**Comment by leikkisa** [comment]
@nanotone I see what you're saying, we don't really have a word for that. We've used "matchable" and "available" before.  I don't have a strong opinion (related works too).  If you think it helps, a comment could make up for an ambiguous name.

**Pull request merged**
