### PR TITLE
  Updating styles for 'Case Not Certified' screen

### PR DESCRIPTION
**Pull request by webinista**
- Adds a color to SVG check mark
- Refactors CSS for reusability with all such message pages
- Changes error controller to use basic layout

### CODE REVIEW

**Comment by paultag** [comment]
@webinista looks good to me - screenshots? I'll assign to Kavi now!

**Comment by webinista** [comment]
screen shot 2015-12-09 at 2 14 12 pm

**Comment by KHarshawat** [comment]
Ahhh... so pretty! Thanks @webinista !!!

**Comment by paultag** [comment]
@webinista Awesome; let's land this - there's a merge conflict, mind merging against master?

**Pull request merged**
