### PR TITLE
bva decision progress sql

### LINKED ISSUE #12074: Test BVA decision progress SQL
Follow on to #11921 

Create tests for the BVA decision progress SQL.

## AC

- [ ] add app/sql/bva-decision-progress.sql
- [ ] specs for app/sql/bva-decision-progress.sql

### PR DESCRIPTION
**Pull request by pkarman**
Resolves #12074 

### Description
Validates the SQL for BVA Decision Progress

### CODE REVIEW

**Comment by lomky** [comment]
@pkarman any indication of which line or character is causing that?

**Comment by pkarman** [comment]
@lomky nope -- see the CircleCI failure on this PR for example

**Comment by lomky** [comment]
Must be different in behavior from looker to psql. Experimenting a bit on the dev psql console, the error pops up once the first `union all` is introduced. A quick swap to `union` doesn't fix it.

Works:
```
caseflow_certification_development=# WITH undistributed_appeals AS (select '1. Not distributed' as decision_status, count(DISTINCT(appeal_id)) as num
            FROM tasks
            WHERE tasks.type IN ('DistributionTask')
              AND tasks.appeal_type='Appeal'
              AND tasks.status IN  ('on_hold', 'assigned', 'in_progress')
-- The Appeal has been distributed to the judge, but not yet assigned to an attorney for working.
      ), distributed_to_judge AS (select '2. Distributed to judge' as decision_status, count(DISTINCT(appeal_id)) as num
            FROM tasks
            WHERE tasks.type IN ('JudgeAssignTask') 
              AND tasks.appeal_type='Appeal'
              AND tasks.status IN  ('assigned', 'in_progress'))
SELECT decision_status, num FROM undistributed_appeals;
```

Stops working:
```
caseflow_certification_development=# WITH undistributed_appeals AS (select '1. Not distributed' as decision_status, count(DISTINCT(appeal_id)) as num
            FROM tasks
            WHERE tasks.type IN ('DistributionTask')
              AND tasks.appeal_type='Appeal'
              AND tasks.status IN  ('on_hold', 'assigned', 'in_progress')
-- The Appeal has been distributed to the judge, but not yet assigned to an attorney for working.
      ), distributed_to_judge AS (select '2. Distributed to judge' as decision_status, count(DISTINCT(appeal_id)) as num
            FROM tasks
            WHERE tasks.type IN ('JudgeAssignTask') 
              AND tasks.appeal_type='Appeal'
              AND tasks.status IN  ('assigned', 'in_progress')
)
SELECT decision_status, num FROM undistributed_appeals
UNION ALL 
SELECT decision_status, num FROM distributed_to_judge;
```

**Comment by pkarman** [comment]
found the problem. Postgresql needs an explicit cast for literal strings like `'foo'::text`.

**Pull request merged**
