### PR TITLE
Marian 877 cancellation

### PR DESCRIPTION
**Pull request by mmlumba**
Fixing modal to be prose case
References #877 
screen shot 2017-02-17 at 9 59 06 am

### CODE REVIEW

**Comment by mmlumba** [comment]
@lakohl 
screen shot 2017-02-17 at 11 25 46 am

**Comment by mmlumba** [comment]
@lakohl 
screen shot 2017-02-17 at 11 38 48 am

**Comment by lakohl** [comment]
Great!

**Comment by mmlumba** [comment]
Could you approve the PR on Github please? @lakohl

**Pull request merged**
