### PR TITLE
Testing JIRA Smart Commits

### PR DESCRIPTION
**Pull request by hschallhorn**
[CASEFLOW-44]

### CODE REVIEW

**Comment by NateMartinTista** [comment]
CASEFLOW-44 #comment This is a test comment from Nate.

**Comment by NateMartinTista** [comment]
CASEFLOW-44 #Start Work

**Comment by NateMartinTista** [comment]
CASEFLOW-44 #COMMENT Testing after updating my primary email address

**Comment by NateMartinTista** [comment]
CASEFLOW-44 #comment Another test.

**Comment by NateMartinTista** [comment]
CASEFLOW-44 #comment Testing, testing, 1, 2, 3!

**Comment by NateMartinTista** [comment]
#CASEFLOW-44 #Start Work

**Comment by NateMartinTista** [comment]
[CASEFLOW-44] #comment This is a test comment using a smart commit

**Comment by NateMartinTista** [comment]
[CASEFLOW-44] #comment This is a test of Smart Commits functionality 1:41pm

**Comment by NateMartinTista** [comment]
CASEFLOW-44 #comment another Test

**Comment by GabbyTISTA** [comment]
Using this comment to avoid getting booted out of VA Github 👍

**Pull request closed without merging**
