### PR TITLE
Show withdrawn status for request issues

### LINKED ISSUE #10760: Add withdrawn dispositions to request issues in Case Details
Sometimes, request issues have dispositions. Veterans can opt to withdraw a request issue, or a request issue could be stayed. Judges and other VA employees need to see that request issues already have dispositions, and therefore don't need a decision. 

There are three places where we want to show request issue dispositions, if they exist:
- Case details
- Attorney check out flow
- Judge check out flow

Epic: #8936 
Related: Create AMA issues component - #8591 

## AC

- If a request issue has a closed status  of withdrawn, show that disposition in case details
- If a request issue has a closed status of withdrawn, show that disposition in check out flows
- Require decision issues on withdrawn request issues in check out flow.
- Treat withdrawn decision issues the same way that we treat denied decision issues, but with the disposition of withdrawn. This allows Veterans to appeal their withdrawal (e.g. if the Board misinterpreted that the Veteran wanted to withdraw). 

## Tech notes
- You might hear people say "request issue dispositions". That's referring to request issue closed statuses.
- Contestable issues are our own decision issues + ratings from BGS. If we don't create a new rating with the denial in BGS as a result of the withdrawal, we'd need to create a Caseflow decision issue with a disposition. That decision issue would be contestable, but it wouldn't be connected to a BGS rating. 

### Provocation design for case details view of **single-withdrawn issue**
Screen Shot 2019-05-15 at 11 25 49 AM

### PR DESCRIPTION
**Pull request by monfresh**
If a request issue has been withdrawn, we want that to be apparent in
the case details view.

Resolves #10760

### CODE REVIEW

**Comment by monfresh** [comment]
Screenshot of issue displayed on case details page after attorney checkout:
Screen Shot 2019-06-27 at 11 54 15 AM

**Comment by monfresh** [comment]
Screenshot showing withdrawn status after decision issue has been added:
Screen Shot 2019-06-27 at 3 44 42 PM

**Comment by monfresh** [comment]
Screenshot of visiting appeals page after attorney checkout:
Screen Shot 2019-06-28 at 10 58 00 AM

**Comment by monfresh** [comment]
Screenshot showing decision issue being created for withdrawn request issue:
Screen Shot 2019-06-28 at 12 08 21 PM

**Comment by monfresh** [comment]
Screenshot showing withdrawn status when judge views case details after attorney assigns it to them:
Screen Shot 2019-06-28 at 4 41 15 PM

**Comment by laurjpeterson** [comment]
@monfresh - could you change "WITHDRAWN" to be "Withdrawn"? And change "Closed status" to read "Disposition"? I think those will be more clear for users.

cc: @sneha-pai - Moncef adjusted the design a little bit for easier initial implementation and test coverage. He's going to be out of the office for some of this week, then on bat team next week, so we discussed deploying it with this design, and revisiting when he's back.

**Comment by monfresh** [comment]
@lauren Here's an updated screenshot:
Screen Shot 2019-07-01 at 2 52 18 PM

**Pull request merged**
