### PR TITLE
Adds x close button to modal. closes #397

### LINKED ISSUE #397: Add a close button (X) to top right of the modal

### LINKED ISSUE #408: Low priority: Make clicking / hitting `Esc` key to close modal also update/blank out the hash
Related to #397

### LINKED ISSUE #411: Make cf-action-close a little less abstract
Rename it to `.cf-action-closemodal` and make it specifically a control for modals

### PR DESCRIPTION
**Pull request by webinista**
Also refactors close modal JS so that close modal button, ESC key, and
clicking on modal background use the same `$.fn.closeModal` method.

closes #408
closes #411 

Moves some existing JS around so to add a reusable $.fn.openModal method.

### CODE REVIEW

**Comment by webinista** [comment]
Screen shots to show the button and its `:hover`/ `:focus`/ `:active` state.

screen shot 2015-12-17 at 10 08 17 am

## `:hover`/ `:focus`/ `:active` state
screen shot 2015-12-17 at 10 08 25 am

**Comment by alex** [comment]
Merge conflicts here too :-(

**Comment by alex** [comment]
more merge conflicts :-(

**Comment by KHarshawat** [comment]
@webinista visual/ux lgtm!

**Comment by alex** [comment]
@webinista I attempted to resolve teh merge conflict, can you confirm I didn't screw it up horribly :-)

**Comment by alex** [comment]
Interesting bug, when I click the "X", the browser window scrolls to the top of the page, rather than leaving me where I am.

**Comment by webinista** [comment]
Browsers treat an empty hash as an indication that the page should jump to the top. Unexpected, but how they work.

Unfortunately, while working on a fix for it, I realized that there's an even bigger issue with using `:target` since we've decided to use `window.history.back()`. See #432. 

Still need to merge this because it adds the close button. I'll leave it to someone else to decide whether that merge needs to wait for a fix in #432.

**Comment by alex** [comment]
One more issue I noticed: if I have the modal up, and I click elsewhere on the page (outside the modal) to close it, it still scrolls up to the top. Probably a missing `e.preventDefault()` there?

**Comment by webinista** [comment]
I can't duplicate that bug @alex. Are you still seeing it after updating the branch? All of the modal controls use the same `closeModal` method, so it's odd that it one control would trigger different behavior.

**Comment by alex** [comment]
No longer able to reproduce, assuming it was cache.

**Pull request merged**
