### PR TITLE
Add extra context to Sentry event for VBMS upload jobs

### PR DESCRIPTION
**Pull request by nanotone**
### Description
This PR provides additional context on UploadDocumentToVbmsJob runs to Raven, so that Sentry events come with:
- `vbms_uploaded_document_id` - the ID of the document being uploaded
- `case_details_path` - path to the associated case details page

As requested by Paul Saindon, the `case_details_path` will also be included with Sentry alerts in Slack, via the sentry-to-slack lambda.

### Acceptance Criteria
- [ ] Code compiles correctly

### CODE REVIEW

**Comment by yoomlam** [comment]
Context: https://dsva.slack.com/archives/CD5DAQNCU/p1627479018046500

**Review by yoomlam — COMMENTED** [review]
Do you want to include the user who initiated the job from here: https://github.com/department-of-veterans-affairs/caseflow/blob/b146c1f577a0856e82ef3ba0a4b74644c4b8cd82/app/workflows/prepare_document_upload_to_vbms.rb#L18

**Comment by nanotone** [comment]
> Do you want to include the user who initiated the job here:
> 
> https://github.com/department-of-veterans-affairs/caseflow/blob/b146c1f577a0856e82ef3ba0a4b74644c4b8cd82/app/workflows/prepare_document_upload_to_vbms.rb#L18-L20

That's probably much more effort than it's worth, because the VbmsUploadedDocument record is the only way to share data between the job initiation context (IDT request handler) and the job run itself. And that table would need a migration to start storing the user...

**Comment by yoomlam** [comment]
> > Do you want to include the user who initiated the job here:
> > https://github.com/department-of-veterans-affairs/caseflow/blob/b146c1f577a0856e82ef3ba0a4b74644c4b8cd82/app/workflows/prepare_document_upload_to_vbms.rb#L18-L20
> 
> That's probably much more effort than it's worth, because the VbmsUploadedDocument record is the only way to share data between the job initiation context (IDT request handler) and the job run itself. And that table would need a migration to start storing the user...

Could you not pass the user as an argument to this call: `UploadDocumentToVbmsJob.perform_later(document_id: document.id)`? 
Wouldn't it be passed to https://github.com/department-of-veterans-affairs/caseflow/blob/e6b852b9f4da812dcdfbd9b63e6b8e520b9c368e/app/jobs/upload_document_to_vbms_job.rb#L7
which you can then pass to https://github.com/department-of-veterans-affairs/caseflow/blob/e6b852b9f4da812dcdfbd9b63e6b8e520b9c368e/app/jobs/upload_document_to_vbms_job.rb#L12

See https://github.com/department-of-veterans-affairs/caseflow/pull/9941/files

**Comment by nanotone** [comment]
Oh, I see what you were referring to the first time, and yeah I forgot that we totally can pass data through the job initiation itself. Pushing an update shortly.

**Comment by nanotone** [comment]
@yoomlam - pushed up new code to include the user information.

I chose the slightly awkward word `initiator` to distinguish them from `User.system_user` which is the account that's actually performing the job.

**Review by yoomlam — APPROVED** [review]
Nice!

**Pull request merged**
