### PR TITLE
Use date input type for dates. Closes #292

### LINKED ISSUE #292: Use input type date for all form 8 fields
Right now, all input fields that have dates use `<input type="text"...>` because IE11 does not support the date type. However, IE11 will switch them to text fields as a default, so this should still work even though the user will not benefit from its use.

Low priority enhancement.

### PR DESCRIPTION
**Pull request by webinista**
- Also changes the way date format is printed to HTML and sent back to the controller.

*This should really be tested heavily before deploying to prod.*

### CODE REVIEW

**Comment by paultag** [comment]
Will test this on IE

**Comment by paultag** [comment]
OK, thoughts:

  - It falls back to regular input field on IE, which seems fine
  - As a result, the format for the date is going to change to ISO (YYYY-MM-DD) -- which, for the record, I prefer -- but is different from the formatting on the form (or what they'd enter)


Is there an IE compatible shim that provides a datetime picker via jQuery (or something) for IE 11? It might be possible to degrade well here

**Comment by webinista** [comment]
I can add that for cases when the `date` type isn't supported. **BUT** here's the issue: when the form is submitted using a browser that supports the `date` input type, it will always be sent as `yyyy-mm-dd`. When it's submitted using IE11, it will be sent in `mm/dd/yyyy` format. We'll need to handle both formats on the server. (I'll also try to do this on the front end.)

**Comment by paultag** [comment]
@webinista can we stop-gap IE with jquery.ui.datepicker or something similar?

**Comment by webinista** [comment]
@paultag yes. that's the plan.

**Comment by paultag** [comment]
OK Cool. Want to do it in this PR, so that we don't have to worry about two different date formats?

**Comment by webinista** [comment]
@paultag that's the plan, but it's a more complicated than just "add jquery.datepicker." i want to be sure that we're solving both of the problems identified in this thread and in https://github.com/department-of-veterans-affairs/caseflow/issues/292#issuecomment-163355701:

1. the format of the date _as the user enters and views it_
2. the format of the date _as sent to the controller_ -- specifically, ensuring that it's always the same, regardless of the browser and version used.

jquery.datepicker solves problem 1, but not problem 2.

**Comment by webinista** [comment]
As suggested, I added jquery.datepicker which solves the _date picker_ part of the problem, for IE11, but not the _date format_ part of the problem. Setting the `dateFormat` option OF `jquery.datepicker()` to `yy-mm-dd` still means the user will see a _yyyy-mm-dd_ formatted date. _YYYY-mm-dd_ was identified as a problem, but it only affects IE11.

To solve the date format problem _in browsers that do not support `input type=date`_, I also added:

- A method to reformat dates from _YYYY-MM-DD_ to MM/DD/YYYY
- Methods that update a `hidden` form field with a _YYYY-MM-DD_ formatted date whenever the original date input is changed.
- That method also moves the `name` attribute of each date form field to the `hidden` field so that it's the only value sent to the controller.

@KHarshawat Since there wasn't a design for this, I just added some CSS styling that's inline with the USA Style Guide. Please review.

screen shot 2015-12-14 at 4 26 42 pm

**Comment by alex** [comment]
merge conflicts :-(

**Comment by plusjeff** [comment]
@webinista Is this ready? If so, feel free to assign to someone for last review (happy to volunteer).

**Comment by webinista** [comment]
@plusjeff  Yes, it is if these tests pass no additional merge is required

**Comment by plusjeff** [comment]
Tests out great in IE 11 :smile:

**Pull request merged**
