### PR TITLE
Marian organize special issues into two columns

### PR DESCRIPTION
**Pull request by mmlumba**
This puts the issues into two columns. See screenshot:
screen shot 2017-01-30 at 10 23 43 pm

Referencing issue #625

### CODE REVIEW

**Comment by lakohl** [comment]
@mmlumba I think you put the wrong screenshot at the top?

**Comment by mmlumba** [comment]
@lakohl sorry, the correct one should be up now.

**Comment by lakohl** [comment]
@mmlumba from what I can tell, your right column needs to move 10 pixels to the right. That would make your left column 30 px from the left side of the stage and the right column 30 px from the center - e.g. evenly balanced

**Comment by mmlumba** [comment]
@lakohl see screenshot below:
screen shot 2017-01-31 at 10 27 24 am

**Comment by lakohl** [comment]
@mmlumba I believe you moved the second column 10pixels to the left, it needed to move 10px to the right. Now it needs to move 20 px to the right.

**Comment by KHarshawat-gov** [comment]
@mmlumba there should be a bit more spacing b/t the first and 2nd questions:

image

**Comment by mmlumba** [comment]
New screenshot after label spacing:
screen shot 2017-02-01 at 10 35 31 am

Per my conversation with Kavi @lakohl should talk with @lakohl regarding the rest of the style changes for Special Issues. It seems a ticket has been created for fixing the style issues here: https://github.com/department-of-veterans-affairs/caseflow/issues/715

**Comment by lakohl** [comment]
@mmlumba the screenshot looks much better. I'm confused by your message above. However there is indeed an issue #715 to clean up special issues.

**Comment by KHarshawat-gov** [comment]
@lakohl I looked at the CSS that @mmlumba is using, the way she has it now is correct. The width of the first and second column is even. If we moved the column to the left or right by any pixels one column would be bigger than the other.

**Comment by KHarshawat-gov** [comment]
Also the fixes in #715 look great.

**Comment by lakohl** [comment]
@mmlumba @KHarshawat My bad. I left out the right margin in my math...

**Pull request merged**
